// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = Arduino-Mega
// Board = Arduino Mega
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
//typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  16000000

#define _const_main__led_0 13

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

#define _const_pin__d0 0
#define _const_pin__d1 1
#define _const_pin__d2 2
#define _const_pin__d3 3
#define _const_pin__d4 4
#define _const_pin__d5 5
#define _const_pin__d6 6
#define _const_pin__d7 7
#define _const_pin__d8 8
#define _const_pin__d9 9
#define _const_pin__d10 10
#define _const_pin__d11 11
#define _const_pin__d12 12
#define _const_pin__d13 13
#define _const_pin__d14 14
#define _const_pin__d15 15
#define _const_pin__d16 16
#define _const_pin__d17 17
#define _const_pin__d18 18
#define _const_pin__d19 19
#define _const_pin__d22 22
#define _const_pin__d23 23
#define _const_pin__d24 24
#define _const_pin__d25 25
#define _const_pin__d26 26
#define _const_pin__d27 27
#define _const_pin__d28 28
#define _const_pin__d29 29
#define _const_pin__d30 30
#define _const_pin__d31 31
#define _const_pin__d32 32
#define _const_pin__d33 33
#define _const_pin__d34 34
#define _const_pin__d35 35
#define _const_pin__d36 36
#define _const_pin__d37 37
#define _const_pin__d38 38
#define _const_pin__d39 39
#define _const_pin__d40 40
#define _const_pin__d41 41
#define _const_pin__d42 42
#define _const_pin__d43 43
#define _const_pin__d44 44
#define _const_pin__d45 45
#define _const_pin__d46 46
#define _const_pin__d47 47
#define _const_pin__d48 48
#define _const_pin__d49 49
#define _const_pin__d50 50
#define _const_pin__d51 51
#define _const_pin__d52 52
#define _const_pin__d53 53
#define _const_pin__d54 54
#define _const_pin__d55 55
#define _const_pin__d56 56
#define _const_pin__d57 57
#define _const_pin__d58 58
#define _const_pin__d59 59
#define _const_pin__d60 60
#define _const_pin__d61 61
#define _const_pin__d62 62
#define _const_pin__d63 63
#define _const_pin__d64 64
#define _const_pin__d65 65
#define _const_pin__d66 66
#define _const_pin__d67 67
#define _const_pin__d68 68
#define _const_pin__d69 69
#define _const_pin__input 0
#define _const_pin__output 1
#define _const_pin__in_pullup 2

#define pin__high(name) digitalWrite(name, HIGH)

#define pin__low(name) digitalWrite(name, LOW)

#define pin__read(name)  digitalRead(name)

#define pin__setup(name, mode) pinMode(name, mode)

#define pin__write(name, val) digitalWrite(name, val)

#define _const_adc__ch0 54
#define _const_adc__ch1 55
#define _const_adc__ch2 56
#define _const_adc__ch3 57
#define _const_adc__ch4 58
#define _const_adc__ch5 59
#define _const_adc__ch6 60
#define _const_adc__ch7 61
#define _const_adc__ch8 62
#define _const_adc__ch9 63
#define _const_adc__ch10 64
#define _const_adc__ch11 65
#define _const_adc__ch12 66
#define _const_adc__ch13 67
#define _const_adc__ch14 68
#define _const_adc__ch15 69

#define adc__read(name)  analogRead(name)

#define _const_pwm__ch0 2
#define _const_pwm__ch1 3
#define _const_pwm__ch2 4
#define _const_pwm__ch3 5
#define _const_pwm__ch4 6
#define _const_pwm__ch5 7
#define _const_pwm__ch6 8
#define _const_pwm__ch7 9
#define _const_pwm__ch8 10
#define _const_pwm__ch9 11
#define _const_pwm__ch10 12
#define _const_pwm__ch11 13

#define pwm__write(name, value) analogWrite(name, value)

void setup() {
	pin__setup(_const_pin__d5, _const_pin__output); 
	while( true ) {
		u16 value = (u16)(adc__read(_const_adc__ch5)); 
		pwm__write(_const_pin__d5, (u8)(value / 4)); 
		time__sleep_ms(100); 
	} 
}

void loop(){
}
