// This C code was automatically generated by Aixt Project
// Device = PIC16F886
// Board = Nothing
// Backend = c


#include <xc.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#define _XTAL_FREQ 10000000
#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator: High-speed crystal/resonator on RA6/OSC2/CLKOUT and RA7/OSC1/CLKIN)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled and can be enabled by SWDTEN bit of the WDTCON register)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config MCLRE = OFF      // RE3/MCLR pin function select bit (RE3/MCLR pin function is digital input, MCLR internally tied to VDD)
#pragma config CP = OFF         // Code Protection bit (Program memory code protection is disabled)
#pragma config CPD = OFF        // Data Code Protection bit (Data memory code protection is disabled)
#pragma config BOREN = OFF      // Brown Out Reset Selection bits (BOR disabled)
#pragma config IESO = OFF       // Internal External Switchover bit (Internal/External Switchover mode is disabled)
#pragma config FCMEN = OFF      // Fail-Safe Clock Monitor Enabled bit (Fail-Safe Clock Monitor is disabled)
#pragma config LVP = OFF		// Low Voltage Programming Enable bit (RB3/PGM pin has PGM function, low voltage programming enabled)
#pragma config BOR4V = BOR40V   // Brown-out Reset Selection bit (Brown-out Reset set to 4.0V)
#pragma config WRT = OFF        // Flash Program Memory Self Write Enable bits (Write protection off)
#define time__sleep_ms(TIME)    __delay_ms(TIME)  // implementing by a macro for saving memory
#define time__sleep_us(TIME)    __delay_us(TIME)  // implementing by a macro for saving memory
#define time__sleep(TIME)    __delay_ms(TIME*1024)  // implementing by a macro for saving memory
#define uart__println(MSG)		uart__print(MSG);  uart__write('\n');  uart__write('\r')
#define uart__write(DATA)   while (TRMT == 0);    TXREG = DATA
#define	uart__any()		RCIF

void uart__setup(uint32_t baudrate) ;
void uart__print(char* msg);
uint8_t uart__read() ;



void uart__setup(uint32_t baudrate) { 
    // int16_t n = (uint8_t)(_XTAL_FREQ / (16 * baudrate)) - 1;  
    // if (n < 0)  n = 0; 
    // if (n > 255) {  // low speed
    //     n = (uint8_t)(_XTAL_FREQ / (64 * baudrate)) - 1;
    //     if (n > 255) n = 255;
    //     TXSTAbits.BRGH = 0;   // low speed
    // } else {    // high speed
    //     TXSTAbits.BRGH = 1;   // high speed
    // }
    // SPBRG = n;

    SPBRG = (uint8_t)(_XTAL_FREQ / (64 * baudrate)) - 1;  
    TXSTAbits.BRGH = 0;   // low speed

    TXSTAbits.SYNC = 0;   // Asyncronous
    TXSTAbits.TXEN = 1;   // Tx enabled
    TXSTAbits.TX9 = 0;    // 8 bits

    RCSTAbits.RC9 = 0;    // 8 bits
    RCSTAbits.CREN = 1;   // Rx enabled

    RCSTAbits.SPEN  = 1;  // serial port enabled
}


void uart__print(char* msg){
    while(*msg != '\0') {
        uart__write(*msg);
        msg++;
    }
}


uint8_t uart__read() {
  while (RCIF == 0) ;  // wait for data receive
  if (OERR) {   // if there is overrun error
    CREN = 0;   // clear overrun error bit
    CREN = 1;
  }
  return RCREG; // read from EUSART receive data register
}


void main(void) {

uart__setup(9600);
while(true) {
uart__write('f');
time__sleep_ms(500);
}
}