// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c


#include "CH57x_common.h"
#define true 1
#define time__sleep_ms(TIME)    DelayMs(TIME)
#define time__sleep(TIME)    DelayMs(TIME*1000)
#define time__sleep_us(TIME)    DelayUs(TIME)
#define uart.println(MSG)		uart.print(MSG);  uart.write('\n');  uart.write('\r')
#define uart.any() R8_UART0_RFC
#define	uart.write(DATA)	R8_UART0_THR = DATA
#include <stdio.h>

char __temp_str[80];



void main__init() {
}


void uart.print(char* msg){
    while(*msg != '\0'){
        uart.write(*msg);
        msg++;
    }
}


uint8_t uart.read(void){
    while(!(R8_UART0_RFC == 1)){}
    return R8_UART0_RBR; 
}


void uart.setup(uint32_t baud_rate){
    UART0_BaudRateCfg(baud_rate);
    R8_UART0_FCR = (2 << 6) | RB_FCR_TX_FIFO_CLR | RB_FCR_RX_FIFO_CLR | RB_FCR_FIFO_EN;
    R8_UART0_LCR = RB_LCR_WORD_SZ;
    R8_UART0_IER = RB_IER_TXD_EN;
    R8_UART0_DIV = 1;

    GPIOB_SetBits(GPIO_Pin_7);
    GPIOB_ModeCfg(GPIO_Pin_4, GPIO_ModeIN_PU);   //RX
    GPIOB_ModeCfg(GPIO_Pin_7, GPIO_ModeOut_PP_5mA);  //TX
}


int main(void) {
main__init();
uart.setup(115200);
uint8_t count = 0;
while(true) {
uart.print("counter");
sprintf(__temp_str, " = %u...", (unsigned int)count);
uart.println(__temp_str);
count++;
time__sleep_ms(500);
}
return 0;
}