// This C code was automatically generated by Aixt Project
// Device = PIC16F84
// Board = ---
// Backend = c

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>

#define _XTAL_FREQ 4000000

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer (WDT disabled)
#pragma config PWRTE = ON       // Power-up Timer Enable bit (Power-up Timer is disabled)
#pragma config CP = OFF         // Code Protection bit (Code protection disabled)

#define time__sleep_ms(tms) __delay_ms(tms)

#define time__sleep(ts) __delay_ms(ts << 10)

#define time__sleep_us(tus) __delay_us(tus)

enum port__Port__names {
	port__a = 0,
	port__b,
	port__c,
	port__d,
	port__e,
};

#define port__read(name)  (unsigned char)(*(&PORTA + name))

#define port__setup(name, mode) *(&TRISA + name) = mode

#define port__write(name, value) *(&(PORTA) + name) = value

const unsigned char sequence[8] = {(unsigned char)(0b0000), 0b0001, 0b0011, 0b0111, 0b1111, 0b1110, 0b1100, 0b1000};

void main(void) {
	port__setup(port__b, 0b11110000); 
	while(true) {
		for(int __i_1 = 0; __i_1 < 8; __i_1++) {
			unsigned char step = sequence[__i_1];
			port__write(port__b, step);
			time__sleep_ms(250);
		}
	} 
}
