// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = PIC12F629
// Board = ---
// Backend = c

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _const_ext__irq_in_use true
#define _const_ext__rising 1
#define _const_ext__falling 0
#define ext__setup(edge) INTEDG = edge
#define ext__irq_enable() \
GIE = 1; \
INTE = 1; 
#define ext__irq_disable() INTE = 0
#define _const_pin_fn__io0 0
#define _const_pin_fn__io1 1
#define _const_pin_fn__io2 2
#define _const_pin_fn__io3 3
#define _const_pin_fn__io4 4
#define _const_pin_fn__io5 5
#define _const_pin_fn__irq 2
#define _const_pin_fn__output 0
#define _const_pin_fn__input 1
#define pin_fn__setup(id, mode) \
if( mode == 1 ) { \
	TRISIO |= (0x01 << id);  \
} \
else { \
	TRISIO &= ~(0x01 << id);  \
}; 
#define pin_fn__high(id) GPIO |= 0x01 << id
#define pin_fn__low(id) GPIO &= ~(0x01 << id)
#define pin_fn__write(id, value) \
GPIO &= (~(0x01 << id)); \
GPIO |= (value << id); 
#define pin_fn__toggle(id) GPIO ^= 0x01 << id
#define pin_fn__read(id)  ((u8) (u8)((GPIO >> id) & 0x01))

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000

void (*ptr_ext_isr)(void);

#define _XTAL_FREQ _const_main__cpu_freq

#pragma config MCLRE = OFF      // Master Clear Enable
#pragma config CP = OFF         // Code Protection
#pragma config BOREN = OFF      // Brown-out Reset Enable
#pragma config WDTE = OFF       // Watchdog Timer Enable
#pragma config FOSC = INTRCIO   // Internal RC oscilator
#pragma config PWRTE = ON       // Power-up timer

#if defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)   // if any interrupt source is activated

#ifdef _const_ext__irq_in_use
void (*ptr_ext_isr)(void);      // Interrupt Service Routine pointer
#endif  // _const_ext__irq_in_use

#ifdef _const_timer0__irq_in_use
void (*ptr_timer0_isr)(void);   // Interrupt Service Routine pointer
#endif  // _const_timer0__irq_in_use

void __interrupt() Global_ISR() {
	#ifdef _const_ext__irq_in_use
	if(INTF == 1) {
		ptr_ext_isr();
		INTF = 0;
	}
	#endif  // _const_ext__irq_in_use
	
	#ifdef _const_timer0__irq_in_use
	if(T0IF == 1) {
		ptr_timer0_isr();
		T0IF = 0;
	}
	#endif  // _const_timer0__irq_in_use
}

#endif  // defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)

void  main__toggle_led() {
	pin_fn__toggle(_const_pin_fn__io1); 
}

void main(void) {
	ptr_ext_isr = main__toggle_led;
	pin_fn__setup(_const_pin_fn__io1, _const_pin_fn__output); 
	pin_fn__low(_const_pin_fn__io1); 
	pin_fn__setup(_const_pin_fn__irq, _const_pin_fn__input); 
	ext__setup(_const_ext__falling); 
	ext__irq_enable(); 
	while( true ) {
	} 
}

