// This Arduino code was automatically generated by Aixt Project
// Device = RP2040
// Board = Raspberry Pi Pico
// Backend = arduino

#define led     gp25
#define time.sleep_ms(MS)    delay(MS)
#define output		OUTPUT
#define input		INPUT
#define in_pullup	INPUT_PULLUP
@[inline]
pub fn high(PIN_NAME) {
	C.digitalWrite(PIN_NAME, HIGH)
}
@[inline]
pub fn low(PIN_NAME) {
	C.digitalWrite(PIN_NAME, LOW)
}
@[inline]
pub fn read(PIN_NAME) {
	C.digitalRead(PIN_NAME)
}
@[inline]
pub fn setup(PIN_NAME, MODE) {
	C.pinMode(PIN_NAME, MODE)
}
@[inline]
pub fn write(PIN_NAME, VALUE) {
	C.digitalWrite(PIN_NAME, VALUE)
}

void main__init();

void time.init();

void pin.init();

enum main____pin_names {
	gp0,
	gp1,
	gp2,
	gp3,
	gp4,
	gp5,
	gp6,
	gp7,
	gp8,
	gp9,
	gp10,
	gp11,
	gp12,
	gp13,
	gp14,
	gp15,
	gp16,
	gp17,
	gp18,
	gp19,
	gp20,
	gp21,
	gp22,
	gp23,
	gp24,
	gp25,
	gp26,
	gp27,
	gp28,
	gp29,
};

void main__init() {
	time.init();
	pin.init();
	
}

void time.init() {
}

void pin.init() {
}

void setup() {
	main__init();
	pin.setup(led, output);
	pin.setup(gp11, input);
}

void loop() {
	bool b0n = false;
	if(pin.read(gp11)) {
		time.sleep_ms(50);
		while(pin.read(gp11)) {
		}
		time.sleep_ms(50);
		b0n = !b0n;
		if(b0n) {
			pin.high(led);
		}
		else {
			pin.low(led);
		}
	}
}
