// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = Arduino-Mega
// Board = Arduino Mega
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
//typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  16000000

#define _const_main__led_0 13

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

#define _const_port__b 0
#define _const_port__c 1
#define _const_port__d 2
#define _const_port__e 3
#define _const_port__f 4
#define _const_port__g 5
#define _const_port__h 6
#define _const_port__j 7
#define _const_port__k 8
#define _const_port__all_inputs 0b11111111
#define _const_port__all_outputs 0b00000000

#define port__read(name)  (u8)(*(&PINB + (name * 3)))

#define port__setup(name, mode) *(&DDRB + (name * 3)) = ~mode

#define port__write(name, value) *(&PORTB + (name * 3)) = value

void setup() {
	port__setup(_const_port__b, _const_port__all_inputs); 
	port__setup(_const_port__c, 0b11110000); 
	while( true ) {
		port__write(_const_port__c, port__read(_const_port__b)); 
		time__sleep_ms(100); 
	} 
}

void loop(){
}
