#define M5_LCD_SETBRIGHTNESS(brightness)                                M5.lcd.setBrightness(brightness)
#define M5_LCD_DRAWPIXEL(x, y, color)                                   M5.lcd.drawPixel(x, y, color)
#define M5_LCD_DRAWLINE(x0, y0, x1, y1, color)                          M5.lcd.drawLine(x0, y0, x1, y1, color)
#define M5_LCD_FILLRECT(x, y, w, h, color)                              M5.lcd.fillRect(x, y, w, h, color)
#define M5_LCD_FILLSCREEN(color)                                        M5.lcd.fillScreen(color)
#define M5_LCD_DRAWCIRCLE(x0, y0, r, color)                             M5.lcd.drawCircle(x0, y0, r, color)
#define M5_LCD_DRAWCIRCLEHELPER(x0, y0, r, cornername, color)           M5.lcd.drawCircleHelper(x0, y0, r, cornername, color)
#define M5_LCD_FILLCIRCLE(x0, y0, r, color)                             M5.lcd.fillCircle(x0, y0, r, color)
#define M5_LCD_FILLCIRCLEHELPER(x0, y0, r, cornername, delta, color)    M5.lcd.fillCircleHelper(x0, y0, r, cornername, delta, color)
#define M5_LCD_DRAWTRIANGLE(x0, y0, x1, y1, x2, y2, color)              M5.lcd.drawTriangle(x0, y0, x1, y1, x2, y2, color)
#define M5_LCD_FILLTRIANGLE(x0, y0, x1, y1, x2, y2, color)              M5.lcd.fillTriangle(x0, y0, x1, y1, x2, y2, color)
#define M5_LCD_DRAWROUNDRECT(x0, y0, w, h, radius, color)               M5.lcd.drawRoundRect(x0, y0, w, h, radius, color)
#define M5_LCD_FILLROUNDRECT(x0, y0, w, h, radius, color)               M5.lcd.fillRoundRect(x0, y0, w, h, radius, color)
#define M5_LCD_DRAWBITMAP(x, y, bitmap, w, h, color)                    M5.lcd.drawBitmap(x, y, bitmap, w, h, color)
#define M5_LCD_DRAWRGBBITMAP(x, y, bitmap, w, h)                        M5.lcd.drawRGBBitmap(x, y, bitmap, w, h)
#define M5_LCD_DRAWCHAR(x, y, c, color, bg, size)                       M5.lcd.drawChar(x, y, c, color, bg, size)
#define M5_LCD_SETCURSOR(x0, y0)                                        M5.lcd.setCursor(x0, y0)
#define M5_LCD_SETTEXTCOLOR(color)                                      M5.lcd.setTextColor(color)
#define M5_LCD_SETTEXTCOLORBG(color, bgcolor)                           M5.lcd.setTextColor(color, bgcolor)
#define M5_LCD_SETTEXTSIZE(size)                                        M5.lcd.setTextSize(size)
#define M5_LCD_SETTEXTWRAP(w)                                           M5.lcd.setTextWrap(w)
#define M5_LCD_PRINT(str)                                               M5.lcd.print(str)
#define M5_LCD_PRINTLN(str)                                             M5.lcd.println(str)
#define M5_LCD_DRAWCENTRESTRING(str, dx, poy, font)                     M5.lcd.drawCentreString(str, dx, poy, font)
#define M5_LCD_DRAWRIGHTSTRING(str, dx, poy, font)                      M5.lcd.drawRightString(str, dx, poy, font)
#define M5_LCD_DRAWJPG(jpg_data, jpg_len, x, y)                         M5.lcd.drawJpg(jpg_data, jpg_len, x, y)
#define M5_LCD_DRAWJPGFILE(fs, path, x, y)                              M5.lcd.drawJpgFile(fs, path, x, y)
#define M5_LCD_DRAWBMPFILE(fs, path, x, y)                              M5.lcd.drawBmpFile(fs, path, x, y)
#define M5_LCD_CLEAR(color)                                             M5.Lcd.clear(color)
#define M5_LCD_DRAWRECT(x, y, w, h, color)                              M5.Lcd.drawRect(x, y, w, h, color) 
#define M5_LCD_WIDTH()                                                  M5.Lcd.width()
#define M5_LCD_HEIGHT()                                                 M5.Lcd.height()