// This C code was automatically generated by Aixt Project
// Device = PIC24FJ128GA010
// Board = Explorer 16
// Backend = native

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>
#include "/home/aixt-project/ports/Microchip/Explorer16/PIC24/api/builtin.c"
#include "/home/aixt-project/ports/Microchip/Explorer16/PIC24/api/machine/pin.c"
#include "/home/aixt-project/ports/Microchip/Explorer16/PIC24/api/time/sleep_ms.c"

#define FCY 4000000UL

#pragma config POSCMOD = XT
#pragma config OSCIOFNC = ON
#pragma config FCKSM = CSDCMD
#pragma config FNOSC = PRI
#pragma config IESO = ON
#pragma config WDTPS = PS32768
#pragma config FWPSA = PR128
#pragma config WINDIS = ON
#pragma config FWDTEN = OFF
#pragma config ICS = PGx2
#pragma config GWRP = OFF
#pragma config GCP = OFF
#pragma config JTAGEN = OFF

int main(void ) {
	pin_mode(a7, out);
	while(true) {
		pin_high(a7);
		sleep_ms(500);
		pin_low(a7);
		sleep_ms(500);
	}
	return 0;
}