// This Arduino code was automatically generated by Aixt Project
// Device = WeAct-Studio
// Board = ESP32-C3FH4
// Backend = arduino

#define pin__output    OUTPUT
#define pin__input     INPUT
#define pin__high(PIN_NAME)    digitalWrite(PIN_NAME, HIGH)
#define pin__low(PIN_NAME)      digitalWrite(PIN_NAME, LOW)
#define pin__read(PIN_NAME)     digitalWrite(PIN_NAME)
#define pin__setup(PIN_NAME, MODE)      pinMode(PIN_NAME, MODE)
#define pin__write(PIN_NAME, VALUE)     digitalWrite(PIN_NAME, VALUE)
#define adc__read(PIN_NAME)     analogRead(PIN_NAME)
#define pwm__write(PIN, VALUE)	analogWrite(PIN, VALUE)
#define time__sleep(TIME)      delay(TIME*1000)
#define time__sleep_ms(TIME)      delay(TIME)
#define time__sleep_us(TIME)      delayMicroseconds(TIME)

void main__init();

void pin__init();

void adc__init();

void pwm__init();

void time__init();

int32_t volumen = 0;

void main__init() {
	pin__init();
	adc__init();
	pwm__init();
	time__init();
	
}

void pin__init() {
}

void adc__init() {
}

void pwm__init() {
}

void time__init() {
}

void setup() {
	main__init();
}

void loop() {
	volumen = adc__read(3);
	pwm__write(7, volumen);
}
