// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void  main__init();
void  main__clear_screen();
long pin__pins[8] = {0, 0, 0, 0, 0, 0, 0, 0};
long pin__input = 0;

void  pin__update();
void  pin__init();
long  pin__read(long name);
void  pin__high(long name);
void  pin__toggle(long name);
void  pin__low(long name);
void  pin__write(long name, long val);
void  time__sleep_ms(long tms);
void  time__sleep(long ts);

void  main__init() {
	main__init();
	pin__init();
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	main__init();
	pin__init();
	
	// linux
	system("clear");; 
	
}
const long pin__a = 0;
const long pin__b = 1;
const long pin__c = 2;
const long pin__d = 3;
const long pin__w = 4;
const long pin__x = 5;
const long pin__y = 6;
const long pin__z = 7;

void  pin__update() {
	main__init();
	pin__init();
	
	// linux
	system("clear");; 
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n"); 
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n"); 
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n"); 
	for(int i=0; i<8; i++) { 
		printf("| ["); 
		if(i <= 3) {
			printf("\033[1;32m");
		}
		else 
		{
			printf("\033[1;31m");
		}; 
		if(pin__pins[i] == 0) {
			printf(" ");
		}
		else 
		{
			printf("#");
		}; 
		printf("\033[1;37m"); 
		printf("] "); 
	} 
	printf("|\n"); 
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n"); 
	
}

void  pin__init() {
	main__init();
	pin__init();
	
	pin__update(); 
	
}

long  pin__read(long name) {
	main__init();
	pin__init();
	
	long pin__value = 0; 
	// linux
	system("clear");; 
	printf(" Aixt virtual pins input	  pin %ld : ", name); 
	scanf("%ld", &pin__value); 
	if(pin__value == 0) {
		pin__pins[name] = 0;
	}
	else 
	{
		pin__pins[name] = 1;
	}; 
	pin__update(); 
	return pin__value; 
	
}

void  pin__high(long name) {
	main__init();
	pin__init();
	
	pin__pins[name] = 1; 
	pin__update(); 
	
}

void  pin__toggle(long name) {
	main__init();
	pin__init();
	
	pin__pins[name] ^= 1; 
	pin__update(); 
	
}

void  pin__low(long name) {
	main__init();
	pin__init();
	
	pin__pins[name] = 0; 
	pin__update(); 
	
}

void  pin__write(long name, long val) {
	main__init();
	pin__init();
	
	pin__pins[name] = val; 
	pin__update(); 
	
}
// linux;

inline void  time__sleep_ms(long tms) {
	main__init();
	pin__init();
	
	// linux
	usleep(tms * 1000);; 
	
}

inline void  time__sleep(long ts) {
	main__init();
	pin__init();
	
	// linux
	sleep(ts);; 
	
}

int main() {
	main__init();
	pin__init();
	
	pin__update(); 
	time__sleep_ms(2000); 
	pin__high(pin__a); 
	pin__write(pin__b, 1); 
	time__sleep(2); 
	pin__low(pin__a); 
	time__sleep(2); 
	pin__write(pin__b, 0); 
	return 0;
}
