// This Arduinocode was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = arduino



#include <stdbool.h>
#include "/home/aixt-project/ports/Emulator/api/builtin.c"
#include "/home/aixt-project/ports/Emulator/api/time/sleep_us.c"
#include "/home/aixt-project/ports/Emulator/api/machine/pin.c"


void setup() {
	pin_update();
	sleep_us(500000);
	for(int i=0; i<5; i++) {
		pin_high(a);
		sleep_us(500000);
		pin_low(a);
		sleep_us(500000);
	}
}