// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "./ports/Emulator/api/builtin.c"
#include "./ports/Emulator/api/machine/pin.c"
#include "./ports/Emulator/api/time/sleep.c"


int main() {
	pin_update();
	sleep(1);
	for(int i=0; i<5; i++) {
		pin_high(a);
		sleep(1);
		pin_low(a);
		sleep(1);
	}
	return 0;
}