// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>

void main__init();

enum main__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void main__init() {
}

int main() {
	main__init();
	char var[80];
	var = input("Enter a string: ");
	print("Echo: ");
	println(var);
	return 0;
}
