// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#define time__sleep(TIME)		sleep(TIME)

void main__init();

void pin__write(long pin_name, long val);

void pin__high(long pin_name);

void pin__low(long pin_name);

long pins__[] = {0, 0, 0, 0, 0, 0, 0, 0};

long input__ = 0;

void pin__update();

enum main__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void main__init() {
}

void pin__write(long pin_name, long val) {
	pins__[pin_name] = val;
	pin__update();
}

void pin__high(long pin_name) {
	pins__[pin_name] = 1;
	pin__update();
}

void pin__low(long pin_name) {
	pins__[pin_name] = 0;
	pin__update();
}

void pin__update() {
	system("clear");
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n");
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n");
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n");
	for(long i__ = 0; i__ <= 7; i__++) {
		if(pins__[i__] == 0) {
			printf("| [ ] ");
		}
		else {
			printf("| [#] ");
		}
	}
	printf("|\n");
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n");
}

int main() {
	main__init();
	for(int i=1; i<10; i++) {
		pin__write(y, high);
		time__sleep(1);
		pin__write(y, low);
		time__sleep(1);
	}
	return 0;
}
