// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
void  uart__println(char msg[]);
char __temp_str[80];

void  main__init() {
	main__init();
	uart__init();
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	main__init();
	uart__init();
	
	// linux
	system("clear");; 
	
}

void  uart__init() {
	main__init();
	uart__init();
	
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
	
}

inline void  uart__println(char msg[]) {
	main__init();
	uart__init();
	
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
	
}

int main() {
	main__init();
	uart__init();
	
	strcpy(s1, "Hola"); 
	strcpy(s2, " mundo!"); 
	strcpy(s, strcat(strcpy(__temp_str, s1), s2)); 
	uart__println(s); 
	return 0;
}
