// This C code was automatically generated by Aixt Project
// Device = PIC16F886
// Board = ---
// Backend = c

#include <xc.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _XTAL_FREQ 10000000

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator: High-speed crystal/resonator on RA6/OSC2/CLKOUT and RA7/OSC1/CLKIN)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled and can be enabled by SWDTEN bit of the WDTCON register)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config MCLRE = OFF      // RE3/MCLR pin function select bit (RE3/MCLR pin function is digital input, MCLR internally tied to VDD)
#pragma config CP = OFF         // Code Protection bit (Program memory code protection is disabled)
#pragma config CPD = OFF        // Data Code Protection bit (Data memory code protection is disabled)
#pragma config BOREN = OFF      // Brown Out Reset Selection bits (BOR disabled)
#pragma config IESO = OFF       // Internal External Switchover bit (Internal/External Switchover mode is disabled)
#pragma config FCMEN = OFF      // Fail-Safe Clock Monitor Enabled bit (Fail-Safe Clock Monitor is disabled)
#pragma config LVP = OFF		// Low Voltage Programming Enable bit (RB3/PGM pin has PGM function, low voltage programming enabled)

// CONFIG2
#pragma config BOR4V = BOR40V   // Brown-out Reset Selection bit (Brown-out Reset set to 4.0V)
#pragma config WRT = OFF        // Flash Program Memory Self Write Enable bits (Write protection off)

// // interrupt macros
// #define irq_enable()	GIE = 1	
// #define irq_disable()	GIE = 0

// #define	irq_external_enable()	INTE = 1
// #define	irq_external_clear()	INTF = 0
// #define	irq_external_rising()	INTEDG = 1
// #define	irq_external_falling()	INTEDG = 0
// #define irq_external(FN_NAME)	void __interrupt(irq(INT),high_priority) FN_NAME(void)

#define time__sleep(ts) __delay_ms(ts << 10)

#define time__sleep_ms(tms) __delay_ms(tms)

#define time__sleep_us(tus) __delay_us(tus)

#define _const_pin__a0 0
#define _const_pin__a1 1
#define _const_pin__a2 2
#define _const_pin__a3 3
#define _const_pin__a4 4
#define _const_pin__a5 5
#define _const_pin__a6 6
#define _const_pin__a7 7
#define _const_pin__b0 8
#define _const_pin__b1 9
#define _const_pin__b2 10
#define _const_pin__b3 11
#define _const_pin__b4 12
#define _const_pin__b5 13
#define _const_pin__b6 14
#define _const_pin__b7 15
#define _const_pin__c0 16
#define _const_pin__c1 17
#define _const_pin__c2 18
#define _const_pin__c3 19
#define _const_pin__c4 20
#define _const_pin__c5 21
#define _const_pin__c6 22
#define _const_pin__c7 23
#define _const_pin__d0 24
#define _const_pin__d1 25
#define _const_pin__d2 26
#define _const_pin__d3 27
#define _const_pin__d4 28
#define _const_pin__d5 29
#define _const_pin__d6 30
#define _const_pin__d7 31
#define _const_pin__e0 32
#define _const_pin__e1 33
#define _const_pin__e2 34
#define _const_pin__e3 35
#define _const_pin__e4 36
#define _const_pin__e5 37
#define _const_pin__e6 38
#define _const_pin__e7 39
#define _const_pin__output 0
#define _const_pin__input 1

#define pin__read(name)  (u8)((*(&PORTA + (name >> 3)) >> (name - ((name >> 3) << 3))) & 0x01)

#define pin__toggle(name) *(&PORTA + (name >> 3)) ^= (i32)(0x01 << (name - ((name >> 3) << 3)))

#define pin__low(name) *(&PORTA + (name >> 3)) &= (i32)(~(0x01 << (name - ((name >> 3) << 3))))

#define pin__write(name, value) \
*(&PORTA + (name >> 3)) &= (i32)((~(0x01 << (name - ((name >> 3) << 3))))); \
*(&PORTA + (name >> 3)) |= (i32)((value << (name - ((name >> 3) << 3)))); \
// end #define

#define pin__setup(name, mode) \
if( mode == 1 ) { \
	*(&TRISA + (name >> 3)) |= (i32)((0x01 << (name - ((name >> 3) << 3))));  \
} \
else { \
	*(&TRISA + (name >> 3)) &= (i32)(~(0x01 << (name - ((name >> 3) << 3))));  \
}; \
// end #define

#define pin__high(name) *(&PORTA + (name >> 3)) |= (i32)(0x01 << (name - ((name >> 3) << 3)))

#define _const_port__a 0
#define _const_port__b 1
#define _const_port__c 2
#define _const_port__d 3
#define _const_port__e 4

#define port__read(name)  (u8)(*(&PORTA + name))

#define port__write(name, value) *(&(PORTA) + name) = (i32)(value)

#define port__setup(name, mode) *(&TRISA + name) = (i32)(mode)

#define _const_adc__in0 0b1111111111111110
#define _const_adc__in1 0b1111111111111101
#define _const_adc__in2 0b1111111111111011
#define _const_adc__in3 0b1111111111110111
#define _const_adc__in4 0b1111111111101111
#define _const_adc__in5 0b1111111111011111
#define _const_adc__in6 0b1111111110111111
#define _const_adc__in7 0b1111111101111111
#define _const_adc__in8 0b1111111011111111
#define _const_adc__in9 0b1111110111111111
#define _const_adc__in10 0b1111101111111111
#define _const_adc__f_30ksps_1mhz 0
#define _const_adc__f_30ksps_4mhz 1
#define _const_adc__f_18ksps_8mhz 2
#define _const_adc__f_21ksps_10mhz 2
#define _const_adc__f_24ksps_12mhz 2
#define _const_adc__f_30ksps_16mhz 2
#define _const_adc__f_34ksps_20mhz 2
#define _const_adc__f_18ksps_irc 3
#define _const_adc__bits_8 0
#define _const_adc__bits_10 1
#define _const_adc__ch0 0
#define _const_adc__ch1 1
#define _const_adc__ch2 2
#define _const_adc__ch3 3
#define _const_adc__ch4 4
#define _const_adc__ch5 5
#define _const_adc__ch6 6
#define _const_adc__ch7 7
#define _const_adc__ch8 8
#define _const_adc__ch9 9
#define _const_adc__ch10 10

#define adc__read(channel) \
C.ADCON0bits = (void)(channel); \
C.ADCON0bits = (void)(1); \
while( C.ADCON0bits == 1 ) { \
} \
 (u16)((ADRESH << 8) | ADRESL); \
// end #define

#define adc__setup(pins, fad, nbits) \
(u8)(ANSEL) = (u8)((u8)(~pins)); \
ANSELH = (i32)((u8)(~pins >> 8)); \
ADCON1 = (i32)(0b00000000); \
C.ADCON1bits = (void)(nbits); \
C.ADCON0bits = (void)(fad); \
C.ADCON0bits = (void)(1); \
// end #define

void main(void) {
	adc__setup(_const_adc__in0, _const_adc__f_21ksps_10mhz, _const_adc__bits_10); 
	pin__setup(_const_pin__a0, _const_pin__input); 
	port__setup(_const_port__b, port__all_outputs); 
	port__setup(_const_port__c, 0b11111100); 
	u16 value = (u16)(0); 
	while( true ) {
		value = (u16)(adc__read(_const_adc__ch0)); 
		port__write(_const_port__b, (u8)(value)); 
		port__write(_const_port__c, (u8)(value >> 8)); 
		time__sleep_ms(250); 
	} 
}

