// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"

int main() {
	double a = 10.5;
	return 0;
}
