// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>

int main() {
	long a = 245;
	double x = 3.5;
	double y = .46;
	double z = 10.;
	double k = 15e-4;
	double l = 1.2e-3;
	double m = 1e6;
	bool flag_1 = true;
	bool flag_2 = false;
	char str_1[] = "char string";
	char c_1 = 'X';
	return 0;
}
