// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	signed char a = -50 + 37;
	short b = 300;
	long c = -80000;
	long e = 300;
	long long f = -400;
	unsigned char g = 50;
	unsigned short h = 300;
	unsigned long i = 80000;
	unsigned long long k = 400;
	float l = 1.5e-4;
	double m = 4e-12;
	return 0;
}
