// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	long a = 2;
	long b = 1;
	long c = 0;
	c = a + b;
	c = a - b;
	c = a * b;
	c = a / b;
	c = a % b;
	c = a << b;
	c = a >> b;
	c = a | b;
	c = a & b;
	c = a ^ b;
	c = a || b;
	c = a && b;
	return 0;
}
