// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	long a = 0;
	long b = 5;
	bool c = true;
	bool d = false;
	a = -b;
	c = !d;
	return 0;
}
