// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	long x = 0;
	for(long i = 1; i <= 10; i++) {
		x += i;
	}
	return 0;
}
