// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>
#include "/home/aixt-project/ports/PC/api/builtin.c"



int main() {
	long a = 0;
	for(int i=10; i<20; i++) {
		a += i;
	}
	return 0;
}