// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	long a[5] = {1, 3, 4, 5, 6};
	a[0] = 2;
	long b = 3;
	a[b] = 10;
	b = a[4];
	return 0;
}
