// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"


int _t1;


int main() {
	long arr[4] = {2, 4, 9, 7};
	for(int _t1 = 0; _t1 < 0; _t1++) {
		arr[_t1]++;
	}
	return 0;
}
