// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>
#include "/home/aixt-project/ports/PC/api/builtin.c"



int main() {
	long arr[4] = {2, 4, 9, 7};
	for(int _t1 = 0; _t1 < 0; _t1++) {
		arr[_t1]++;
	}
	return 0;
}