// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"




int main() {
	long x = 4;
	long y = 5;
	long z = 6;
	x = 1;
	y = 2;
	z = 3;
	return 0;
}
