// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"
#include "/home/fercho/aixt/ports/Emulator/api/time/sleep.c"
#include "/home/fercho/aixt/ports/Emulator/api/machine.c"




int main() {
	float a = 0.0;
	while(true) {
		sleep(1);
		a++;
	}
	return 0;
}
