// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"
#include <stdio.h>
#include "/home/fercho/aixt/ports/Emulator/api/time/sleep.c"

#define	time	1500

int main() {
	long a = 0;
	while(true) {
		sleep(time);
		a = ;
	}
	return 0;
}
