// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"


int main() {
	long a = 10;
	long b = 20;
	long c = 30;
	b = c + a;
	a = if(b > c) {
		b;
	}
	else {
		c;
	}
	return 0;
}
