// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"



enum Color {
	red = 10,
	blue,
	green,
};enum Zzz {
	transpile,
	uh,
	transpile_file,
};
int main() {
	toml.Any(toml.Null{}) c1 = green;
	toml.Any(toml.Null{}) c2 = uh;
	toml.Any(toml.Null{}) c3 = red;
	return 0;
}
