// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c



#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"



long w = 10;
float x = 12.5;
const char y = 'm';
const long z = 23;

int main() {
	long a = 12;
	float b = 3.4;
	char c = 'c';
	char d[] = "str";
	long e[4] = {3, 5, 6, 7};
	return 0;
}
