// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include "/home/fercho/aixt/ports/Emulator/api/builtin.c"

int main() {
	signed char a = 4;
	signed char b = 7;
	signed char c = 0;
	c = average_8b(a, a + b);
	return 0;
}
signed char average_8b(signed char x, signed char y) {
	long n = 2;
	return (signed char)((x + y) / n);
}

