// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdio.h>

void main__init();

enum main__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void main__init() {
}

int main() {
	main__init();
	char name[] = "Fernando";
	long age = 43;
	println();
	return 0;
}
