// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = CY8CKIT-049
// Board = CY8CKIT-049-42XX
// Backend = c
#include "project.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int32_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint32_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

// Project Name: Aixt https://github.com/fermarsan/aixt.git
// Author: Fernando M. Santa - Daniel Polo - Edwin Barrera - Javier Leon - Camilo Lucas
// Date: 2022-2025
// License: MIT
//
// // Description: builtin (CY8CKIT-049-42XX)

#define INIT_INTERRUPTS()   CyGlobalIntEnable

void  main__init();
u16  adc__read(i32 channel);
char __temp_str[20];

#define _const_main__led1 led1
#define _const_main___led2 led2
#define _const_main__do0 3
#define _const_main__do1 4
#define _const_main__do2 5
#define _const_main__do3 6
#define _const_main__do4 7
#define _const_main__do5 8
#define _const_main__do6 9
#define _const_main__do7 10
#define _const_main__do8 11
#define _const_main__do9 12
#define _const_main__do10 13
#define _const_main__sw1 sw1
#define _const_main__di0 20
#define _const_main__di1 21
#define _const_main__di2 22
#define _const_main__di3 23
#define _const_main__di4 24
#define _const_main__di5 25
#define _const_main__di6 26
#define _const_main__di7 27
#define _const_main__di8 28
#define _const_main__di9 29
#define _const_main__di10 30

void  main__init() {
	INIT_INTERRUPTS(); 
}

#define _const_adc__ch0 0
#define _const_adc__ch1 1
#define _const_adc__ch2 2
#define _const_adc__ch3 3

inline u16  adc__read(i32 channel) {
	amux_FastSelect(channel); 
	CyDelay(5); 
	adc_StartConvert(); 
	while( !adc_IsEndConversion(adc_RETURN_STATUS) ) { 
	} 
	adc_StopConvert(); 
	return adc_GetResult16(0); 
}

#define adc__setup() \
adc_Start(); \
amux_Start(); 

#define uart__print(message) uart_UartPutString(message)

#define uart__println(message) \
uart_UartPutString(message); \
uart_UartPutChar(0x0D); \
uart_UartPutChar(0x0A); 

#define uart__read()  uart_UartGetChar()

#define uart__setup() uart_Start()

#define uart__write(character) uart_UartPutChar(character)

#define time__sleep_ms(tms) CyDelay(tms)

#define time__sleep_us(tus) CyDelayUs(tus)

int main() {
	main__init();
	uart__setup(); 
	adc__setup(); 
	while( true ) {
		u16 analog = (u16)(adc__read(_const_adc__ch0)); 
		sprintf(__temp_str, "ADC channel 0: %u", (unsigned int)analog);
		uart__println(__temp_str); 
		time__sleep_ms(1000); 
	} 
	return 0;
}

