// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>


#include "/home/aixt-project/ports/PC/api/time.c"
#include "/home/aixt-project/ports/PC/api/machine/pin.c"

int main() {
	pin_update();
	sleep_ms(1500);
	pin_high(A);
	pin_write(B, 1);
	sleep_us(1500000);
	pin_low(A);
	sleep(2);
	pin_write(B, 0);
	return 0;
}