// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c


#include "CH57x_common.h"
#define true 1
#define uart__println(MSG)		uart__print(MSG);  uart__write('\n');  uart__write('\r')
#define uart__any()  R8_UART0_RFC
#define	uart__write(DATA)	R8_UART0_THR = DATA

void uart__print(char* msg);
uint8_t uart__read(void);
void uart__setup(uint32_t baud_rate);



void uart__print(char* msg){
    while(*msg != '\0'){
        uart__write(*msg);
        msg++;
    }
}


uint8_t uart__read(void){
    while(!(R8_UART0_RFC == 1)){}
    return R8_UART0_RBR; 
}


void uart__setup(uint32_t baud_rate){
    UART0_BaudRateCfg(baud_rate);
    R8_UART0_FCR = (2 << 6) | RB_FCR_TX_FIFO_CLR | RB_FCR_RX_FIFO_CLR | RB_FCR_FIFO_EN;
    R8_UART0_LCR = RB_LCR_WORD_SZ;
    R8_UART0_IER = RB_IER_TXD_EN;
    R8_UART0_DIV = 1;

    GPIOB_SetBits(GPIO_Pin_7);
    GPIOB_ModeCfg(GPIO_Pin_4, GPIO_ModeIN_PU);   //RX
    GPIOB_ModeCfg(GPIO_Pin_7, GPIO_ModeOut_PP_5mA);  //TX
}


int main(void) {

char input = ' ';
uart__setup(115200);
while(true) {
if(uart__any()) {input = uart__read();uart__write((uint8_t)(input) + 1);};
}
return 0;
}