// This Arduino code was automatically generated by Aixt Project
// Device = AIR32F103
// Board = AIR32F103
// Backend = arduino

@[inline]
pub fn adc.read(PIN_NAME) {
C.analogRead(PIN_NAME)
}
#define output		OUTPUT
#define input		INPUT
#define in_pullup	INPUT_PULLUP
@[inline]
pub fn pin.high(PIN_NAME) {
	C.digitalWrite(PIN_NAME, HIGH)
}
@[inline]
pub fn pin.low(PIN_NAME) {
	C.digitalWrite(PIN_NAME, LOW)
}
@[inline]
pub fn pin.read(PIN_NAME) {
	C.digitalRead(PIN_NAME)
}
@[inline]
pub fn pwm.setup(PIN_NAME, MODE) {
	C.pinMode(PIN_NAME, MODE)
}
@[inline]
pub fn pwm.write(PIN_NAME, VALUE) {
	C.digitalWrite(PIN_NAME, VALUE)
}
@[inline]
pub fn pwm.map(MODE, VALUE,VALUE1,VALUE2,VALUE3) {
	C.map(MODE, VALUE,VALUE1,VALUE2,VALUE3)
}
@[inline]
pub fn pwm.write(PIN_NAME, MODE) {
	C.pwmWrite(PIN_NAME, MODE)
}

void main__init();

void adc.init();

void pin.init();

void pwm.init();

enum main____pin_names {
	rx = PA9,
	tx = PA10,
	p1 = PA0,
	p2 = PA1,
	p3 = PA2,
	p4 = PA3,
	p5 = PA4,
	p6 = PA5,
	p7 = PA6,
	p8 = PA7,
	p9 = PA8,
	p10 = PA13,
	p11 = PA14,
	p12 = PA15,
	p13 = PB0,
	p14 = PB1,
	p15 = PB2,
	p16 = PB3,
	p17 = PB4,
	p18 = PB5,
	p19 = PB6,
	p20 = PB7,
	p21 = PB8,
	p22 = PB9,
	p23 = PB10,
	p24 = PB11,
	p25 = PB12,
	p26 = PB13,
	p27 = PB14,
	p28 = PB15,
};

void main__init() {
	adc.init();
	pin.init();
	pwm.init();
	
}

void adc.init() {
}

void pin.init() {
}

void pwm.init() {
}

void setup() {
	main__init();
	pin.setup(p13, input);
	pin.setup(p20, PWM);
	adc.read(p5);
	pwm.map(adc.read(p5), 4095, 0, 4095, 0);
	pwm.write(p13, PWM);
}
