#define HIGH_FAST(PORT_NAME,PIN)  R##PORT_NAME##PIN = 1
#define LOW_FAST(PORT_NAME,PIN)  R##PORT_NAME##PIN  = 0
#define READ_FAST(PORT_NAME,PIN)  R##PORT_NAME##PIN
#define SETUP_FAST(PORT_NAME,PIN,MODE)  TRIS##PORT_NAME##PIN = MODE
#define TOGGLE_FAST(PORT_NAME,PIN)  R##PORT_NAME##PIN = ~ R##PORT_NAME##PIN 
#define WRITE_FAST(PORT_NAME,PIN,VALUE)  R##PORT_NAME##PIN = VALUE