// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = T-WATCH-2020
// Board = ESP32-WROOM-32
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int32_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint32_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  240000000

// #define lv__align_center    LV_ALIGN_CENTER

void setup() {
}

void loop(){
}

const i32 _const_lv__align_center = (i32)(LV_ALIGN_CENTER);

#define lv__scr_act()  lv_scr_act()

#define lv__label_create(active_scr)  lv_label_create(active_scr, NULL)

#define lv__label_set_text(label, msg) lv_label_set_text(label, msg)

#define lv__obj_align(obj, align, x, y) lv_obj_align(obj, NULL, align, x, y)

#define lv__task_handler() lv_task_handler()
