// This Arduino code was automatically generated by Aixt Project
// Device = RP2040
// Board = Raspberry Pi Pico
// Backend = arduino

<<<<<<< HEAD:ports/Ai-Thinker/Ai-WB2-32S-Kit/example/pwm/pwm.ino
#define time__sleep_ms(MS)    delay(MS)
=======
#define led     gp25
#define time__sleep(S)    delay(S*1000)
>>>>>>> e2001e18f72232dc1682e8a0f1e8f9ed11a0959c:ports/Raspberry-Pi/Raspberry-Pi-Pico/projects/BLINKING/blinking/blinking.ino
#define output		OUTPUT
#define input		INPUT
#define in_pullup	INPUT_PULLUP
#define pin.high(PIN_NAME)   digitalWrite(PIN_NAME, HIGH)
#define pin.low(PIN_NAME)   digitalWrite(PIN_NAME, LOW)
#define pin.read(PIN_NAME)   digitalRead(PIN_NAME)
#define pin.setup(PIN_NAME, MODE)    pinMode(PIN_NAME, MODE)
#define pin.write(PIN_NAME, VALUE)   digitalWrite(PIN_NAME, VALUE)

void main__init();

void time__init();

void pin.init();

void main__init() {
	time__init();
	pin.init();
	
}

void time__init() {
}

void pin.init() {
}

void setup() {
	main__init();
<<<<<<< HEAD:ports/Ai-Thinker/Ai-WB2-32S-Kit/example/pwm/pwm.ino
	pin.setup(17, output);
=======
	pin.setup(led, output);
>>>>>>> e2001e18f72232dc1682e8a0f1e8f9ed11a0959c:ports/Raspberry-Pi/Raspberry-Pi-Pico/projects/BLINKING/blinking/blinking.ino
}

void loop() {
	pin.low(led);
	time__sleep(2);
	pin.high(led);
	time__sleep(2);
}
