// This Arduino code was automatically generated by Aixt Project
// Device = RP2040
// Board = Raspberry Pi Pico
// Backend = arduino

<<<<<<< HEAD:ports/Ai-Thinker/Ai-WB2-32S-Kit/example/pwm/pwm.ino
#define time.sleep_ms(MS)    delay(MS)
=======
#define led     gp25
#define time.sleep(S)    delay(S*1000)
>>>>>>> e2001e18f72232dc1682e8a0f1e8f9ed11a0959c:ports/Raspberry-Pi/Raspberry-Pi-Pico/projects/BLINKING/blinking/blinking.ino
#define output		OUTPUT
#define input		INPUT
#define in_pullup	INPUT_PULLUP
@[inline]
pub fn pin.high(PIN_NAME) {
	C.digitalWrite(PIN_NAME, HIGH)
}
@[inline]
pub fn pin.low(PIN_NAME) {
	C.digitalWrite(PIN_NAME, LOW)
}
@[inline]
pub fn pin.read(PIN_NAME) {
	C.digitalRead(PIN_NAME)
}
@[inline]
pub fn pwm.setup(PIN_NAME, MODE) {
	C.pinMode(PIN_NAME, MODE)
}
@[inline]
pub fn pwm.write(PIN_NAME, VALUE) {
	C.digitalWrite(PIN_NAME, VALUE)
}

void main__init();

void time.init();

void pin.init();

void main__init() {
	time.init();
	pin.init();
	
}

void time.init() {
}

void pin.init() {
}

void setup() {
	main__init();
<<<<<<< HEAD:ports/Ai-Thinker/Ai-WB2-32S-Kit/example/pwm/pwm.ino
	pin.setup(17, output);
=======
	pin.setup(led, output);
>>>>>>> e2001e18f72232dc1682e8a0f1e8f9ed11a0959c:ports/Raspberry-Pi/Raspberry-Pi-Pico/projects/BLINKING/blinking/blinking.ino
}

void loop() {
	pin.low(led);
	time.sleep(2);
	pin.high(led);
	time.sleep(2);
}
