// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>

#include "/home/aixt-project/ports/PC/api/builtin.c"

#include "/home/aixt-project/ports/PC/api/time/sleep_us.c"
#include "/home/aixt-project/ports/PC/api/machine/pin.c"

int main() {
	pin_update();
	sleep_us(500000);
	for(int i=0; i<5; i++) {
		pin_high(a);
		sleep_us(500000);
		pin_low(a);
		sleep_us(500000);
	}
	return 0;
}