// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>

#include "/home/aixt-project/ports/PC/api/builtin.c"

#include "/home/aixt-project/ports/PC/api/os.c"

int main() {
	__string_add(__temp_str, "Heloo world!");
	println(__temp_str);
	return 0;
}