// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>

#include "/home/aixt-project/ports/PC/api/builtin.c"

#include "/home/aixt-project/ports/PC/api/os.c"

int main() {
	char str1[80];
	__string_assign(str1, "Hello world!");
	println(str1);
	return 0;
}