// This C code was automatically generated by Aixt Project
// Device = PIC16F84A
// Board = Nothing
// Backend = c

#include <xc.h>
#include <stdio.h>
#define _XTAL_FREQ 4000000
#define true   1
#define false  0
#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer (WDT disabled)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (Power-up Timer is disabled)
#pragma config CP = OFF         // Code Protection bit (Code protection disabled)
#define TRISa		TRISA	// port setup name equivalents
#define TRISb		TRISB
#define PORTa		PORTA	// port in name equivalents
#define PORTb		PORTB
#define a0_s    TRISAbits.TRISA0    // pin configuration pits
#define a1_s    TRISAbits.TRISA1
#define a2_s    TRISAbits.TRISA2
#define a3_s    TRISAbits.TRISA3
#define b0_s    TRISBbits.TRISB0
#define b1_s    TRISBbits.TRISB1
#define b2_s    TRISBbits.TRISB2
#define b3_s    TRISBbits.TRISB3
#define b4_s    TRISBbits.TRISB4
#define b5_s    TRISBbits.TRISB5
#define b6_s    TRISBbits.TRISB6
#define b7_s    TRISBbits.TRISB7
#define a0    PORTAbits.RA0       // pin input and output pits
#define a1    PORTAbits.RA1
#define a2    PORTAbits.RA2
#define a3    PORTAbits.RA3
#define b0    PORTBbits.RB0
#define b1    PORTBbits.RB1
#define b2    PORTBbits.RB2
#define b3    PORTBbits.RB3
#define b4    PORTBbits.RB4
#define b5    PORTBbits.RB5
#define b6    PORTBbits.RB6
#define b7    PORTBbits.RB7
#define time__sleep_ms(TIME)    __delay_ms(TIME)  // implementing by a macro for saving memory
#define pin__output 0   // pin mode direction
#define pin__input  1
#define pin__high(PIN_NAME)  PIN_NAME = 1
#define pin__low(PIN_NAME)   PIN_NAME = 0
#define pin__read(PIN_NAME)  PIN_NAME
#define pin__setup(PIN_NAME, PIN_MODE)   PIN_NAME ## _s = PIN_MODE
#define pin__write(PIN_NAME,VAL) PIN_NAME = VAL

void main__init();

void time__init();

void pin__init();

void main__init() {
	time__init();
	pin__init();
	
}

void time__init() {
}

void pin__init() {
}

void main(void) {
	main__init();
	pin__setup(b0, pin__output);
	pin__setup(b1, pin__output);
	pin__setup(b2, pin__output);
	pin__write(b0, 0);
	pin__write(b1, 0);
	pin__write(b2, 0);
	while(true) {
		pin__high(b0);
		time__sleep_ms(500);
		pin__high(b1);
		time__sleep_ms(500);
		pin__high(b2);
		time__sleep_ms(500);
		pin__low(b0);
		pin__low(b1);
		pin__low(b2);
		time__sleep_ms(500);
	}
}
