// This C code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000
void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
void  uart__println(char msg[]);
void  uart__print(char msg[]);
char*  uart__input(char msg[]);
i32  ex_array__min(array src, u16 len_);
char __temp_str[120];

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	// linux 
	system("clear");; 
}

void  uart__init() {
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
}

void  uart__println(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
}

void  uart__print(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s", msg); 
}

char*  uart__input(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s ", msg); 
	scanf("%s", uart__buffer); 
	return uart__buffer; 
}

i32  ex_array__min(array src, u16 len_) {
	i32 minimum = (i32)(src[0]); 
	for( int i = 1; i < len_; i ++ ) { 
		if( minimum < src[i] ) { 
			minimum = (i32)(minimum);  
		} 
		else { 
			minimum = (i32)(src[i]);  
		}  
	} 
	return minimum; 
}

int main() {
	main__init();
	uart__init();
	i32 my_array[2] = {2, 7, 3, 1, 9}; 
	i32 minimum = (i32)(ex_array__min(my_array, 5)); 
	sprintf(__temp_str, "The minimum of array is: %d", (int)minimum);
	uart__println(__temp_str); 
	return 0;
}

