// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c


#include "CH57x_common.h"
#define true 1
#define uart__println(MSG)		uart__print(MSG);  uart__write('\n');  uart__write('\r')
#define uart__any() R8_UART0_RFC
#define	uart__write(DATA)	R8_UART0_THR = DATA
#define	irq__uart_rx_enable()	UART0_ByteTrigCfg(UART_7BYTE_TRIG);  UART0_INTCfg(ENABLE, RB_IER_RECV_RDY | RB_IER_LINE_STAT);  PFIC_EnableIRQ(UART0_IRQn)
#define irq_uart_rx(FN_NAME)	void isr_uart_rx(void)

void uart__print(char* msg);
uint8_t uart__read(void);
void uart__setup(uint32_t baud_rate);
char input = ' ';
#define irq_uart_rx_isr_exists
irq_uart_rx(uart_eco) {
input = uart__read();
uart__write((uint8_t)(input) + 1);
}



void uart__print(char* msg){
    while(*msg != '\0'){
        uart__write(*msg);
        msg++;
    }
}

uint8_t uart__read(void){
    while(!(R8_UART0_RFC == 1)){}
    return R8_UART0_RBR; 
}


void uart__setup(uint32_t baud_rate){
    UART0_BaudRateCfg(baud_rate);
    R8_UART0_FCR = (2 << 6) | RB_FCR_TX_FIFO_CLR | RB_FCR_RX_FIFO_CLR | RB_FCR_FIFO_EN;
    R8_UART0_LCR = RB_LCR_WORD_SZ;
    R8_UART0_IER = RB_IER_TXD_EN;
    R8_UART0_DIV = 1;

    GPIOB_SetBits(GPIO_Pin_7);
    GPIOB_ModeCfg(GPIO_Pin_4, GPIO_ModeIN_PU);   //RX
    GPIOB_ModeCfg(GPIO_Pin_7, GPIO_ModeOut_PP_5mA);  //TX
}


__attribute__((interrupt("WCH-Interrupt-fast")))
__attribute__((section(".highcode")))
void irq__global_isr(void) {
    #ifdef irq_uart_rx_isr_exists
        if(UART_II_RECV_TOUT) {
            isr_uart_rx();
        }
    #endif
   return;
}




int main(void) {

uart__setup(115200);
irq__uart_rx_enable();
while(true) {
}
return 0;
}
