// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Nano
// Board = Arduino Nano
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  16000000

#define _const_main__led0 13

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

#define _const_port__b 0
#define _const_port__c 1
#define _const_port__d 2
#define _const_port__all_inputs 0b11111111
#define _const_port__all_outputs 0b00000000

#define port__read(name)  (u8)(*(&PINB + (name * 3)))

#define port__write(name, value) *(&PORTB + (name * 3)) = value

#define port__setup(name, mode) *(&DDRB + (name * 3)) = ~mode

const u8 _const_main__y[150] = {(u8)(127), 132, 138, 143, 148, 154, 159, 164, 169, 174, 179, 184, 188, 193, 198, 202, 206, 210, 214, 218, 222, 225, 229, 232, 235, 237, 240, 242, 245, 247, 248, 250, 251, 252, 253, 254, 254, 254, 254, 254, 254, 253, 252, 251, 250, 248, 247, 245, 242, 240, 237, 235, 232, 229, 225, 222, 218, 214, 210, 206, 202, 198, 193, 188, 184, 179, 174, 169, 164, 159, 154, 148, 143, 138, 132, 127, 122, 116, 111, 106, 100, 95, 90, 85, 80, 75, 70, 66, 61, 56, 52, 48, 44, 40, 36, 32, 29, 25, 22, 19, 17, 14, 12, 9, 7, 6, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 9, 12, 14, 17, 19, 22, 25, 29, 32, 36, 40, 44, 48, 52, 56, 61, 66, 70, 75, 80, 85, 90, 95, 100, 106, 111, 116, 122};

void setup() {
	port__setup(_const_port__d, _const_port__all_outputs); 
	while( true ) {
		for( int __i_1 = 0; __i_1 < 150; __i_1 ++ ) {
			u8 y_n = _const_main__y[__i_1];
			port__write(_const_port__d, y_n); 
			time__sleep_us(111); 
		} 
	} 
}

void loop(){
}
