// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;

  main__init();
  main__clear_screen();

  main__init() {
	printf("\033[1;37m"); 
}

  main__clear_screen() {
	// linux 
	system("clear");; 
}

int main() {
	main__init();
	f64 a = (f64)(10.5); 
	return 0;
}

