// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

int main() {
	main__init();
	
	long aa = 245; 
	double xx = 3.5;double yy = .46;double zz = 10.; 
	double k = 15e-4;double l = 1.2e-3;double m = 1e6; 
	bool flag_1 = true;bool flag_2 = false; 
	char str_1[80];
	strcpy(str_1, "char string");char c_1 = 'X'; 
	return 0;
}
