// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

int main() {
	main__init();
	
	signed char a = -50 + 37;short b = 300;long c = -80000; 
	long e = 300;long long f = -400; 
	unsigned char g = 50;unsigned short h = 300;unsigned long i = 80000; 
	unsigned long long k = 400; 
	float l = 1.5e-4; 
	double m = 4e-12; 
	return 0;
}
