// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

int main() {
	main__init();
	
	long a = 10;double b = 2.5; 
	a = 2;b = 6.7; 
	a += 1; 
	a -= 1; 
	a *= 1; 
	a /= 1; 
	a &= 1; 
	a |= 1; 
	a ^= 1; 
	a %= 1; 
	a <<= 1; 
	a >>= 1; 
	return 0;
}
