// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();
signed char  main__average_8b(signed char x, signed char y);

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

signed char  main__average_8b(signed char x, signed char y) {
	
	signed char n = 2; 
	return (signed char)((x + y) / n); 
	
}

int main() {
	main__init();
	
	signed char d = main__average_8b(5, 78); 
	return 0;
}
