// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

int main() {
	main__init();
	
	long a[5] = {1, 3, 4, 5, 6}; 
	a[0] = 2; 
	long b = 3; 
	a[b] = 10; 
	b = a[4]; 
	unsigned short c[1] = {10}; 
	return 0;
}
