// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}
const float pi = 3.141592;
const float e = 2.718281;
const long repetitions = 10;
const float r = 1.76;
const char msg[] = "message 1";

int main() {
	main__init();
	
	double x = 0.0; 
	for(int _=0; _<repetitions; _++) {x += (e * (float)(r)) + (float)((pi / 2));} 
	return 0;
}
