// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

void  main__init();
void  main__clear_screen();

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	// linux 
	system("clear");; 
}

const f64 _const_main__pi = (f64)(3.141592);
const f32 _const_main__e = (f32)(2.718281);
const f64 _const_main__r = (f64)(1.76);
const char _const_main__msg[] = "message 1";
const i32 _const_main__repetitions = (i32)(10);

int main() {
	main__init();
	f64 x = (f64)(0.0); 
	for( int _ = 0; _ < _const_main__repetitions; _ ++ ) {
		x += (f64)((_const_main__e * (f32)(_const_main__r)) + (f32)((_const_main__pi / 2))); 
	} 
	return 0;
}

