// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

int main() {
	main__init();
	
	double a = 10.1; 
	double b = 20.0;long c = 30; 
	if(b > c) {a = b;}else {a = c;} 
	if(a > c) {
		b = a;
	}
	else 
	{
		a = c;
	}; 
	return 0;
}
