// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}
enum main__Color {
	red = 10,
	blue,
	green,
};
enum main__Zzz {
	transpile,
	uh,
	transpile_file,
};

int main() {
	main__init();
	
	enum main__Color  c1 = green; 
	enum main__Zzz  c2 = uh; 
	enum main__Color  c3 = red; 
	return 0;
}


