// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
void  uart__println(char msg[]);

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

void  uart__init() {
	
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
	
}

inline void  uart__println(char msg[]) {
	
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
	
}

int main() {
	main__init();
	uart__init();
	
	uart__println("Hello world..."); 
	return 0;
}
