// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
void  uart__println(char msg[]);
long ga = 10;
signed char gb;
float gc = 3.4;
double gd = 4.6;
char ge[] = "message";

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}

void  uart__init() {
	
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
	
}

inline void  uart__println(char msg[]) {
	
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
	
}
const long ca = 10;
const signed char cb = 25;
const float cc = 3.4;
const double cd = 4.6;
const char ce[] = "message";

int main() {
	main__init();
	uart__init();
	
	uart__println("ce"); 
	return 0;
}
