// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();
long pin__pins[8] = {0, 0, 0, 0, 0, 0, 0, 1};
long pin__input_value = 0;

void  pin__update();
void  pin__init();
long  pin__read(long name);
void  pin__high(long name);
void  pin__toggle(long name);
void  pin__low(long name);
void  pin__write(long name, long val);

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// linux
	system("clear");; 
	
}
enum pin__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void  pin__update() {
	
	// linux
	system("clear");; 
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n"); 
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n"); 
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n"); 
	for(int i=0; i<8; i++) { 
		printf("| ["); 
		if(i <= 3) {
			printf("\033[1;32m");
			pin__pins[i] = 0;
		}
		else 
		{
			printf("\033[1;31m");
		}; 
		if(pin__pins[i] == 0) {
			printf(" ");
		}
		else 
		{
			printf("#");
		}; 
		printf("\033[1;37m"); 
		printf("] "); 
	} 
	printf("|\n"); 
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n"); 
	
}

void  pin__init() {
	
	pin__update(); 
	
}

long  pin__read(long name) {
	
	long pin__input_value = 0; 
	// linux
	system("clear");; 
	printf(" Aixt virtual pins input	  pin %ld : ", name); 
	scanf("%ld", &pin__input_value); 
	if(pin__input_value == 0) {
		pin__pins[name] = 0;
	}
	else 
	{
		pin__pins[name] = 1;
	}; 
	pin__update(); 
	return pin__input_value; 
	
}

void  pin__high(long name) {
	
	pin__pins[name] = 1; 
	pin__update(); 
	
}

void  pin__toggle(long name) {
	
	pin__pins[name] ^= 1; 
	pin__update(); 
	
}

void  pin__low(long name) {
	
	pin__pins[name] = 0; 
	pin__update(); 
	
}

void  pin__write(long name, long val) {
	
	pin__pins[name] = val; 
	pin__update(); 
	
}

int main() {
	main__init();
	pin__init();
	
	pin__high(a); 
	return 0;
}
