// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdlib.h>
#if defined(__linux) || defined(linux)
#define CLEAR_SCREEN    "clear" // for Linux
#else
#define CLEAR_SCREEN    "cls"   // for Windows
#endif
#include <string.h>

enum main__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void main__init() {
	    printf("\033[1;37m");    // white bold text in terminal
}

int main() {
	main__init();
	
	char name[80];
	strcpy(name, "Fernando");
	double height = 1.72;
	long weight = 89;
	main__println();
	return 0;
}
