// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	// linux 
	system("clear");; 
}

int main() {
	main__init();
	
	int32_t a = (int32_t)(5); 
	double b = (double)( (a == 1) ? (1.0) : (a == 2) ? (4.0) : (a == 3) ? (9.0) : (a == 5) ? (25.0) : (0.0) ); 
	return 0;
}

