// This Arduino code was automatically generated by Aixt Project
// Device = T-WATCH-2020
// Board = ESP32-WROOM-32
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int32_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint32_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;

 
struct main__LEDs {
	bool state;
	i64 pin;
	bool is_analog;
	u8 *str;
};

void setup() {
}

void loop(){
}
