// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = Emu
// Board = Linux, Windows and Android
// Backend = c

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000
void  time__sleep(i32 ts);
void  time__sleep_ms(i32 tms);
i32 pin__pins[8] = {0, 0, 0, 0, 0, 0, 0, 0};
int_literal pin__input_value = (int_literal)(0);

void  pin_fn__update();
void  pin_fn__init();
void  pin_fn__high(i32 pin_id);
void  pin_fn__low(i32 pin_id);
i32  pin_fn__read(i32 pin_id);
void  pin_fn__toggle(i32 pin_id);
void  pin_fn__write(i32 pin_id, i32 val);
void  main__init();
void  main__clear_screen();

;

void  time__sleep(i32 ts) {
	sleep(ts);; 
}

void  time__sleep_ms(i32 tms) {
	usleep(tms * 1000);; 
}

const i32 _const_pin_fn__a = (i32)(0);
const i32 _const_pin_fn__b = (i32)(1);
const i32 _const_pin_fn__c = (i32)(2);
const i32 _const_pin_fn__d = (i32)(3);
const i32 _const_pin_fn__w = (i32)(4);
const i32 _const_pin_fn__x = (i32)(5);
const i32 _const_pin_fn__y = (i32)(6);
const i32 _const_pin_fn__z = (i32)(7);

void  pin_fn__update() {
	system("clear");; 
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n"); 
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n"); 
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n"); 
	for( int i = 0; i < 8; i ++ ) { 
		printf("| [");  
		if( i <= 3 ) { 
			printf("\033[1;32m");  
		} 
		else { 
			printf("\033[1;31m");  
		};  
		if( pin__pins[i] == 0 ) { 
			printf(" ");  
		} 
		else { 
			printf("#");  
		};  
		printf("\033[1;37m");  
		printf("] ");  
	} 
	printf("|\n"); 
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n"); 
}

void  pin_fn__init() {
	pin_fn__update(); 
}

inline void  pin_fn__high(i32 pin_id) {
	pin__pins[pin_id] = (i32)(1); 
	pin_fn__update(); 
}

inline void  pin_fn__low(i32 pin_id) {
	pin__pins[pin_id] = (i32)(0); 
	pin_fn__update(); 
}

inline i32  pin_fn__read(i32 pin_id) {
	pin__input_value = (i32)(0); 
	system("clear");; 
	printf(" Aixt virtual pins input\t  pin %d : ", pin_id); 
	scanf("%ld", &pin__input_value); 
	if( pin__input_value == 0 ) { 
		pin__pins[pin_id] = (i32)(0);  
	} 
	else { 
		pin__pins[pin_id] = (i32)(1);  
	}; 
	pin_fn__update(); 
	return ((i32) pin__input_value); 
}

inline void  pin_fn__toggle(i32 pin_id) {
	pin__pins[pin_id] ^= (i32)((i32)(1)); 
	pin_fn__update(); 
}

inline void  pin_fn__write(i32 pin_id, i32 val) {
	pin__pins[pin_id] = (i32)(val); 
	pin_fn__update(); 
}

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	system("clear");; 
}

int main() {
	pin_fn__init();
	main__init();
	time__sleep(1); 
	for( int _ = 0; _ < 5; _ ++ ) {
		pin_fn__high(_const_pin_fn__a); 
		time__sleep_ms(500); 
		pin_fn__low(_const_pin_fn__a); 
		time__sleep_ms(500); 
	} 
	return 0;
}

