#define M5_IMU_INIT()                           M5.IMU.Init()
#define M5_IMU_GETGRES()                        M5.IMU.getGres()
#define M5_IMU_GETARES()                        M5.IMU.getAres()
#define M5_IMU_GETACCELADC(ax, ay, az)          M5.IMU.getAccelAdc(ax, ay, az)
#define M5_IMU_GETGYROADC(gx, gy, gz)           M5.IMU.getGyroAdc(gx, gy, gz)
#define M5_IMU_GETTEMPADC(t)                    M5.IMU.getTempAdc(t)
#define M5_IMU_GETACCELDATA(ax, ay, az)         M5.IMU.getAccelData(ax, ay, az)
#define M5_IMU_GETGYRODATA(gx, gy, gz)          M5.IMU.getGyroData(gx, gy, gz)
#define M5_IMU_GETTEMPDATA(t)                   M5.IMU.getTempData(t)
#define M5_IMU_GETAHRSDATA(pitch, roll, yaw)    M5.IMU.getAhrsData(pitch, roll, yaw)
#define M5_IMU_SETFIFOENABLE(enable_flag)       M5.IMU.setFIFOEnable(enable_flag)
#define M5_IMU_READFIFO()                       M5.IMU.ReadFIFO()
#define M5_IMU_READFIFOBUFF(data_buf, length)   M5.IMU.ReadFIFOBuff(data_buf, length)
#define M5_IMU_READFIFOCOUNT()                  M5.IMU.ReadFIFOCount()
#define M5_IMU_RESTFIFO()                       M5.IMU.RestFIFO()