// This Arduino code was automatically generated by Aixt Project
// Device = ATmega328P
// Board = Arduino Nano
// Backend = arduino

void  time__sleep_ms(int32_t tms);
void  time__sleep(int32_t ts);
void  time__sleep_us(int32_t tus);
int32_t  pin__read(int32_t name);
void  pin__high(int32_t name);
void  pin__setup(int32_t name, int32_t mode);
void  pin__low(int32_t name);
void  pin__write(int32_t name, int32_t val);

enum main__pin_names {
	d0,
	d1,
	d2,
	d3,
	d4,
	d5,
	d6,
	d7,
	d8,
	d9,
	d10,
	d11,
	d12,
	d13,
	d14,
	d15,
	d16,
	d17,
	d18,
	d19,
};

inline void  time__sleep_ms(int32_t tms) {
	
	delay(tms); 
	
}

inline void  time__sleep(int32_t ts) {
	
	delay(ts * 1000); 
	
}

inline void  time__sleep_us(int32_t tus) {
	
	delayMicroseconds(tus); 
	
}
const int8_t pin__input = 0x0;
const int8_t pin__output = 0x1;
const int8_t pin__in_pullup = 0x2;

inline int32_t  pin__read(int32_t name) {
	
	return digitalRead(name); 
	
}

inline void  pin__high(int32_t name) {
	
	digitalWrite(name, HIGH); 
	
}

inline void  pin__setup(int32_t name, int32_t mode) {
	
	pinMode(name, mode); 
	
}

inline void  pin__low(int32_t name) {
	
	digitalWrite(name, LOW); 
	
}

inline void  pin__write(int32_t name, int32_t val) {
	
	digitalWrite(name, val); 
	
}

void setup() {
	
	pin__setup(d13, pin__output); 
	while(true) {pin__high(d13);
		time__sleep(1);
		pin__low(d13);
		time__sleep(1);
	} 
	
}
