// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Uno
// Board = Arduino Uno
// Backend = arduino

void  time__sleep(int16_t ts);
void  time__sleep_ms(int16_t tms);
void  time__sleep_us(int16_t tus);
void  pin__high(uint8_t name);
void  pin__low(uint8_t name);
uint8_t  pin__read(uint8_t name);
void  pin__setup(uint8_t name, uint8_t mode);
void  pin__write(uint8_t name, uint8_t val);

enum main__Pin_names {
	d0 = 0,
	d1,
	d2,
	d3,
	d4,
	d5,
	d6,
	d7,
	d8,
	d9,
	d10,
	d11,
	d12,
	d13,
	d14,
	d15,
	d16,
	d17,
	d18,
	d19,
};
enum main__Pin_modes {
	input = 0,
	output,
	in_pullup,
};
enum main__ADC_pin_names {
	a0 = 14,
	a1,
	a2,
	a3,
	a4,
	a5,
};
enum main__Port__names {
	b = 0,
	c,
	d,
};
enum main__Builtin_names {
	led0 = 13,
};

inline void  time__sleep(int16_t ts) {
	delay(ts * 1000); 
}

inline void  time__sleep_ms(int16_t tms) {
	delay(tms); 
}

inline void  time__sleep_us(int16_t tus) {
	delayMicroseconds(tus); 
}

inline void  pin__high(uint8_t name) {
	digitalWrite(name, HIGH); 
}

inline void  pin__low(uint8_t name) {
	digitalWrite(name, LOW); 
}

inline uint8_t  pin__read(uint8_t name) {
	return digitalRead(name); 
}

inline void  pin__setup(uint8_t name, uint8_t mode) {
	pinMode(name, mode); 
}

inline void  pin__write(uint8_t name, uint8_t val) {
	digitalWrite(name, val); 
}

void setup() {
	pin__setup(d13, pin__output); 
	pin__high(d13); 
	time__sleep_ms(500); 
}


