// This Arduino code was automatically generated by Aixt Project
// Device = RP2040
// Board = Raspberry Pi Pico
// Backend = arduino

#define led     gp25
#define output		OUTPUT
#define input		INPUT
#define in_pullup	INPUT_PULLUP
#define pin.high(PIN_NAME)   digitalWrite(PIN_NAME, HIGH)
#define pin.low(PIN_NAME)   digitalWrite(PIN_NAME, LOW)
#define pin.read(PIN_NAME)   digitalRead(PIN_NAME)
#define pin.setup(PIN_NAME, MODE)    pinMode(PIN_NAME, MODE)
#define pin.write(PIN_NAME, VALUE)   digitalWrite(PIN_NAME, VALUE)
#define adc.read(PIN_NAME)   analogRead(PIN_NAME)

void main__init();

void pin.init();

void adc.init();

int32_t val = 0;

enum main____pin_names {
	gp0,
	gp1,
	gp2,
	gp3,
	gp4,
	gp5,
	gp6,
	gp7,
	gp8,
	gp9,
	gp10,
	gp11,
	gp12,
	gp13,
	gp14,
	gp15,
	gp16,
	gp17,
	gp18,
	gp19,
	gp20,
	gp21,
	gp22,
	gp23,
	gp24,
	gp25,
	gp26,
	gp27,
	gp28,
	gp29,
};

void main__init() {
	pin.init();
	adc.init();
	
}

void pin.init() {
}

void adc.init() {
}

void setup() {
	main__init();
	pin.setup(gp13, output);
	pin.setup(gp14, output);
	pin.setup(gp15, output);
	pin.setup(gp16, output);
}

void loop() {
	val = adc.read(gp27);
	if(val >= 0 && val < 255) {
		pin.high(gp13);
		pin.low(gp14);
		pin.low(gp15);
		pin.low(gp16);
	}
	if(val >= 255 && val < 511) {
		pin.low(gp13);
		pin.high(gp14);
		pin.low(gp15);
		pin.low(gp16);
	}
	if(val >= 511 && val < 767) {
		pin.low(gp13);
		pin.low(gp14);
		pin.high(gp15);
		pin.low(gp16);
	}
	if(val >= 767 && val < 1023) {
		pin.low(gp13);
		pin.low(gp14);
		pin.low(gp15);
		pin.high(gp16);
	}
}
