// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

void  main__init();
void  main__clear_screen();
int32_t pin__pins[8] = {0, 0, 0, 0, 0, 0, 0, 0};
int64_t input_value = (int64_t)(0);

void  pin__update();
void  pin__init();
void  pin__high(int32_t name);
void  pin__low(int32_t name);
int32_t  pin__read(int32_t name);
void  pin__toggle(int32_t name);
void  pin__write(int32_t name, int32_t val);

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	// not linux 
	system("cls");; 
}

enum pin__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void  pin__update() {
	// not linux 
	system("cls");; 
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n"); 
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n"); 
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n"); 
	for( int i = 0; i < 8; i ++ ) { 
		 
		printf("| [");  
		if( i <= 3 ) { 
			 
			printf("\033[1;32m");  
		} 
		else { 
			 
			printf("\033[1;31m");  
		};  
		if( pin__pins[i] == 0 ) { 
			 
			printf(" ");  
		} 
		else { 
			 
			printf("#");  
		};  
		printf("\033[1;37m");  
		printf("] ");  
	} 
	printf("|\n"); 
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n"); 
}

void  pin__init() {
	pin__update(); 
}

void  pin__high(int32_t name) {
	pin__pins[name] = (int32_t)(1); 
	pin__update(); 
}

void  pin__low(int32_t name) {
	pin__pins[name] = (int32_t)(0); 
	pin__update(); 
}

int32_t  pin__read(int32_t name) {
	int32_t input_value = (int32_t)(0); 
	// not linux 
	system("cls");; 
	printf(" Aixt virtual pins input	  pin %ld : ", name); 
	scanf("%ld", &input_value); 
	if( input_value == 0 ) { 
		 
		pin__pins[name] = (int32_t)(0);  
	} 
	else { 
		 
		pin__pins[name] = (int32_t)(1);  
	}; 
	pin__update(); 
	return input_value; 
}

void  pin__toggle(int32_t name) {
	pin__pins[name] ^= (int32_t)((int32_t)(1)); 
	pin__update(); 
}

void  pin__write(int32_t name, int32_t val) {
	pin__pins[name] = (int32_t)(val); 
	pin__update(); 
}

int main() {
	main__init();
	pin__init();
	
	pin__setup(a1, pin__input); 
	pin__setup(a5, pin__output); 
	pin__setup(a6, pin__output); 
	pin__low(a5); 
	pin__low(a6); 
	while( true ) {
		if( 250 >= main__adc__read(a1) ) {
			pin__high(a5); 
			pin__low(a6); 
		}
		else {
			pin__low(a5); 
			pin__high(a6); 
		}; 
	} 
	return 0;
}

