// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Uno
// Board = Arduino Uno
// Backend = arduino

void  pin__high(uint8_t name);
void  pin__low(uint8_t name);
uint8_t  pin__read(uint8_t name);
void  pin__setup(uint8_t name, uint8_t mode);
void  pin__write(uint8_t name, uint8_t val);

enum main__Pin_names {
	d0 = 0,
	d1,
	d2,
	d3,
	d4,
	d5,
	d6,
	d7,
	d8,
	d9,
	d10,
	d11,
	d12,
	d13,
	d14,
	d15,
	d16,
	d17,
	d18,
	d19,
};
enum main__Pin_modes {
	input = 0,
	output,
	in_pullup,
};
enum main__ADC_pin_names {
	a0 = 14,
	a1,
	a2,
	a3,
	a4,
	a5,
};
enum main__Port__names {
	b = 0,
	c,
	d,
};
enum main__Builtin_names {
	led0 = 13,
};

inline void  pin__high(uint8_t name) {
	digitalWrite(name, HIGH); 
}

inline void  pin__low(uint8_t name) {
	digitalWrite(name, LOW); 
}

inline uint8_t  pin__read(uint8_t name) {
	return digitalRead(name); 
}

inline void  pin__setup(uint8_t name, uint8_t mode) {
	pinMode(name, mode); 
}

inline void  pin__write(uint8_t name, uint8_t val) {
	digitalWrite(name, val); 
}

void setup() {
	pin__setup(a1, pin__input); 
	pin__setup(a5, pin__output); 
	pin__setup(a6, pin__output); 
	pin__low(a5); 
	pin__low(a6); 
	while(true) {
		if(250 >= main__adc__read(a1)) {
			pin__high(a5);
			pin__low(a6);
		}
		else 
		{
			pin__low(a5);
			pin__high(a6);
		};
	} 
}


