// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

void  main__init();
void  main__clear_screen();
void  time__sleep(long ts);
void  time__sleep_ms(long tms);
long pwm__duty[2] = {0, 0};

void  pwm__print(long duty);
void  pwm__update();
void  pwm__init();
void  pwm__write(long channel, long duty);

enum main__pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// not linux
	system("cls");; 
	
}
// not linux;

inline void  time__sleep(long ts) {
	
	// not linux
	Sleep(ts * 1000);; 
	
}

inline void  time__sleep_ms(long tms) {
	
	// not linux
	Sleep(tms);; 
	
}
const long pwm__ch0 = 0;
const long pwm__ch1 = 1;

void  pwm__print(long duty) {
	
	for(int i=1; i<51; i++) { 
		if(i <= duty / 2) {
			printf("|");
		}
		else 
		{
			printf("_");
		}; 
	} 
	printf("\n"); 
	
}

void  pwm__update() {
	
	// not linux
	system("cls");; 
	printf(" Aixt virtual PWM outputs\n"); 
	printf("\t\t\t\t    PWM 0 :  %ld %%\n", pwm__duty[0]); 
	pwm__print(pwm__duty[0]); 
	printf("\t\t\t\t    PWM 1 :  %ld %%\n", pwm__duty[1]); 
	pwm__print(pwm__duty[1]); 
	
}

void  pwm__init() {
	
	pwm__update(); 
	
}

void  pwm__write(long channel, long duty) {
	
	pwm__duty[channel] = duty; 
	pwm__update(); 
	
}

int main() {
	main__init();
	pwm__init();
	
	pwm__write(1, 100); 
	for(int i=1; i<51; i++) {time__sleep_ms(500);pwm__write(0, i);pwm__write(1, 100 - i);} 
	return 0;
}
