// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Uno
// Board = Arduino Uno
// Backend = arduino

void  time__sleep(int16_t ts);
void  time__sleep_ms(int16_t tms);
void  time__sleep_us(int16_t tus);
void  pwm__write(uint8_t name, uint8_t value);

enum main__Pin_names {
	d0 = 0,
	d1,
	d2,
	d3,
	d4,
	d5,
	d6,
	d7,
	d8,
	d9,
	d10,
	d11,
	d12,
	d13,
	d14,
	d15,
	d16,
	d17,
	d18,
	d19,
};
enum main__Pin_modes {
	input = 0,
	output,
	in_pullup,
};
enum main__ADC_pin_names {
	a0 = 14,
	a1,
	a2,
	a3,
	a4,
	a5,
};
enum main__Port__names {
	b = 0,
	c,
	d,
};
enum main__Builtin_names {
	led0 = 13,
};

inline void  time__sleep(int16_t ts) {
	delay(ts * 1000); 
}

inline void  time__sleep_ms(int16_t tms) {
	delay(tms); 
}

inline void  time__sleep_us(int16_t tus) {
	delayMicroseconds(tus); 
}

inline void  pwm__write(uint8_t name, uint8_t value) {
	analogWrite(name, value); 
}

void setup() {
	pwm__write(1, 100); 
	for(int i=1; i<51; i++) {
		time__sleep_ms(500);
		pwm__write(0, i);
		pwm__write(1, 100 - i);
	} 
}


