// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

void  main__init();
void  main__clear_screen();
void  time__sleep_ms(long tms);

enum main__pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// not linux
	system("cls");; 
	
}
// not linux;

inline void  time__sleep_ms(long tms) {
	
	// not linux
	Sleep(tms);; 
	
}

int main() {
	main__init();
	
	for(int _=0; _<5; _++) {uart1__println("W801 project");time__sleep_ms(1500);} 
	return 0;
}
