// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
char*  uart__input(char msg[]);
void  uart__print(char msg[]);
void  uart__println(char msg[]);
char __temp_str[80];

enum main__pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void  main__init() {
	
	printf("\033[1;37m"); 
	
}

void  main__clear_screen() {
	
	// not linux
	system("cls");; 
	
}

void  uart__init() {
	
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
	
}

char*  uart__input(char msg[]) {
	
	printf("\033[1;32m"); 
	printf("%s ", msg); 
	scanf("%s", uart__buffer); 
	return uart__buffer; 
	
}

inline void  uart__print(char msg[]) {
	
	printf("\033[1;32m"); 
	printf("%s", msg); 
	
}

inline void  uart__println(char msg[]) {
	
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
	
}

sprintf(__temp_str, "output : %s", input);
int main() {
	main__init();
	uart__init();
	
	char input[80];
	strcpy(input, uart__input("input : ")); 
	uart9__println(__temp_str); 
	return 0;
}
