// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c

#include "CH57x_common.h"
#define true 1
@[inline]
pub fn uart1.println(MSG) {
C.uart1.print(MSG);  uart1.write('\n');  uart1.write('\r')
}
@[inline]
pub fn uart1.any() {
	C.R8_UART1_RFC
}
@[inline]
pub fn uart1.write(DATA) {
C.R8_UART1_THR = DATA
}

void uart1.print(char* msg);
uint8_t uart1.read(void);
void uart1.setup(uint32_t baud_rate);

void uart1.print(char* msg){
    while(*msg != '\0'){
        uart1.write(*msg);
        msg++;
    }
}

uint8_t uart1.read(void){
    while(!(R8_UART1_RFC == 1)){}
    return R8_UART1_RBR; 
}

void uart1.setup(uint32_t baud_rate){
    UART1_BaudRateCfg(baud_rate);
    R8_UART1_FCR = (2 << 6) | RB_FCR_TX_FIFO_CLR | RB_FCR_RX_FIFO_CLR | RB_FCR_FIFO_EN;
    R8_UART1_LCR = RB_LCR_WORD_SZ;
    R8_UART1_IER = RB_IER_TXD_EN;
    R8_UART1_DIV = 1;

    GPIOA_SetBits(GPIO_Pin_9);
    GPIOA_ModeCfg(GPIO_Pin_8, GPIO_ModeIN_PU);   //RX
    GPIOA_ModeCfg(GPIO_Pin_9, GPIO_ModeOut_PP_5mA);  //TX
}

int main(void) {

char input = ' ';
uart1.setup(115200);
while(true) {
if(uart1.any()) {input = uart1.read();uart1.write((uint8_t)(input) + 1);};
}
return 0;
}
