// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Nano
// Board = Arduino Nano
// Backend = arduino

void  time__sleep_ms(int16_t tms);
void  time__sleep(int16_t ts);
void  time__sleep_us(int16_t tus);
int16_t  pin__read(int16_t name);
void  pin__high(int16_t name);
void  pin__setup(int16_t name, int16_t mode);
void  pin__low(int16_t name);
void  pin__write(int16_t name, int16_t val);

enum main__Pin_names {
	pin__d0 = 0,
	pin__d1,
	pin__d2,
	pin__d3,
	pin__d4,
	pin__d5,
	pin__d6,
	pin__d7,
	pin__d8,
	pin__d9,
	pin__d10,
	pin__d11,
	pin__d12,
	pin__d13,
	pin__d14,
	pin__d15,
	pin__d16,
	pin__d17,
	pin__d18,
	pin__d19,
	pin__d20,
	pin__d21,
};
enum main__Pin_modes {
	pin__input = 0,
	pin__output,
	pin__in_pullup,
};
enum main__Analog_pin_names {
	a0 = 14,
	a1,
	a2,
	a3,
	a4,
	a5,
	a6,
	a7,
};

inline void  time__sleep_ms(int16_t tms) {
	delay(tms); 
}

inline void  time__sleep(int16_t ts) {
	delay(ts * 1000); 
}

inline void  time__sleep_us(int16_t tus) {
	delayMicroseconds(tus); 
}

inline int16_t  pin__read(int16_t name) {
	return digitalRead(name); 
}

inline void  pin__high(int16_t name) {
	digitalWrite(name, HIGH); 
}

inline void  pin__setup(int16_t name, int16_t mode) {
	pinMode(name, mode); 
}

inline void  pin__low(int16_t name) {
	digitalWrite(name, LOW); 
}

inline void  pin__write(int16_t name, int16_t val) {
	digitalWrite(name, val); 
}

void setup() {
	pin__setup(pin__b13, pin__output); 
	while(true) {
		pin__high(pin__b13);
		time__sleep_ms(500);
		pin__low(pin__b13);
		time__sleep_ms(500);
	} 
}


