// This Arduino code was automatically generated by Aixt Project
// Device = Arduino-Nano
// Board = Arduino Nano
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

enum main__Builtin_names {
	led0 = 13,
};

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

#define pin__read(name)  digitalRead(name)

#define pin__low(name) digitalWrite(name, LOW)

#define pin__write(name, val) digitalWrite(name, val)

#define pin__setup(name, mode) pinMode(name, mode)

#define pin__high(name) digitalWrite(name, HIGH)

void setup() {
	pin__setup(led0, pin__output); 
	while( true ) {
		pin__high(led0); 
		time__sleep_ms(500); 
		pin__low(led0); 
		time__sleep_ms(500); 
	} 
}

void loop(){
}


