// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = PIC16F630-676
// Board = ---
// Backend = c

#include <xc.h>
#include <stdbool.h>
#include <stdint.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

#define _const_adc__in0 (u8)(0b11111110)
#define _const_adc__in1 (u8)(0b11111101)
#define _const_adc__in2 (u8)(0b11111011)
#define _const_adc__in3 (u8)(0b11110111)
#define _const_adc__in4 (u8)(0b11101111)
#define _const_adc__in5 (u8)(0b11011111)
#define _const_adc__in6 (u8)(0b10111111)
#define _const_adc__in7 (u8)(0b01111111)
#define _const_adc__all_analogs (u8)(0b00000000)
#define _const_adc__all_digitals (u8)(0b11111111)
#define _const_adc__bits_8 0
#define _const_adc__bits_10 1
#define _const_adc__ch0 0
#define _const_adc__ch1 1
#define _const_adc__ch2 2
#define _const_adc__ch3 3
#define _const_adc__ch4 4
#define _const_adc__ch5 5
#define _const_adc__ch6 6
#define _const_adc__ch7 7

#define adc__read(channel) \
({\
	CHS = channel; \
	GO_DONE = 1; \
	while( GO_DONE == 1 ) { \
	} \
	(u16)((ADRESH << 8) | ADRESL); \
})

#define adc__read_byte(channel) \
({\
	CHS = channel; \
	GO_DONE = 1; \
	while( GO_DONE == 1 ) { \
	} \
	(u8)(ADRESH); \
})

#define adc__setup(pins, nbits) \
({\
	ANSEL = ~(u8)(pins); \
	u8 div = (u8)(64); \
	for( int i = 0; i < 6; i ++ ) { \
		if( ((div >> i) * 1000) / _const_main__cpu_freq_mhz >= 1600 && ((div >> i) * 1000) / _const_main__cpu_freq_mhz <= 6400 ) { \
			ADCON1 ( (div == 64) ? (0b01100000) : (div == 32) ? (0b00100000) : (div == 16) ? (0b01010000) : (div == 8) ? (0b00010000) : (div == 4) ? (0b01000000) : (div == 2) ? (0b00000000) : (0b00110000) );  \
		};  \
	} \
	ADCON1 = 0b00000000; \
	ADFM = nbits; \
	ADON = 1; \
})

#define _const_pin__a0 0
#define _const_pin__a1 1
#define _const_pin__a2 2
#define _const_pin__a3 3
#define _const_pin__a4 4
#define _const_pin__a5 5
#define _const_pin__a6 6
#define _const_pin__a7 7
#define _const_pin__b0 8
#define _const_pin__b1 9
#define _const_pin__b2 10
#define _const_pin__b3 11
#define _const_pin__b4 12
#define _const_pin__b5 13
#define _const_pin__b6 14
#define _const_pin__b7 15
#define _const_pin__c0 16
#define _const_pin__c1 17
#define _const_pin__c2 18
#define _const_pin__c3 19
#define _const_pin__c4 20
#define _const_pin__c5 21
#define _const_pin__c6 22
#define _const_pin__c7 23
#define _const_pin__d0 24
#define _const_pin__d1 25
#define _const_pin__d2 26
#define _const_pin__d3 27
#define _const_pin__d4 28
#define _const_pin__d5 29
#define _const_pin__d6 30
#define _const_pin__d7 31
#define _const_pin__e0 32
#define _const_pin__e1 33
#define _const_pin__e2 34
#define _const_pin__e3 35
#define _const_pin__e4 36
#define _const_pin__e5 37
#define _const_pin__e6 38
#define _const_pin__e7 39
#define _const_pin__irq 8
#define _const_pin__output 0
#define _const_pin__input 1
#define _const_pin__port_a A
#define _const_pin__port_b B
#define _const_pin__port_c C
#define _const_pin__port_d D
#define _const_pin__port_e E

#define pin__high(name) *(&PORTA + (name >> 3)) |= 0x01 << (name - ((name >> 3) << 3))

#define pin__low(name) *(&PORTA + (name >> 3)) &= ~(0x01 << (name - ((name >> 3) << 3)))

#define pin__read(name)  (u8)((*(&PORTA + (name >> 3)) >> (name - ((name >> 3) << 3))) & 0x01)

#define pin__setup(name, mode) \
({\
	if( mode == 1 ) { \
		*(&TRISA + (name >> 3)) |= (0x01 << (name - ((name >> 3) << 3)));  \
	} \
	else { \
		*(&TRISA + (name >> 3)) &= ~(0x01 << (name - ((name >> 3) << 3)));  \
	}; \
})

#define pin__toggle(name) *(&PORTA + (name >> 3)) ^= 0x01 << (name - ((name >> 3) << 3))

#define pin__write(name, value) \
({\
	*(&PORTA + (name >> 3)) &= (~(0x01 << (name - ((name >> 3) << 3)))); \
	*(&PORTA + (name >> 3)) |= (value << (name - ((name >> 3) << 3))); \
})

#define _const_port__a 0
#define _const_port__b 1
#define _const_port__c 2
#define _const_port__d 3
#define _const_port__e 4
#define _const_port__all_inputs 0b11111111
#define _const_port__all_outputs 0b00000000

#define port__b_pull_ups(enable) RBPU = (i32)(!enable)

#define port__read(name)  (u8)(*(&PORTA + name))

#define port__setup(name, mode) *(&TRISA + name) = mode

#define port__write(name, value) *(&PORTA + name) = value

void main(void) {
	pin__setup(_const_pin__a0, _const_pin__input); 
	adc__setup(_const_adc__in0, _const_adc__bits_10); 
	port__setup(_const_port__c, 0b11000000); 
	port__setup(_const_port__a, 0b11000011); 
	while( true ) {
		u16 value = (u16)(adc__read(_const_adc__ch0)); 
		port__write(_const_port__c, (u8)(value & 0x003f)); 
		port__write(_const_port__a, (u8)((value & 0x03C0) >> 4)); 
	} 
}

