// Project Name: Aixt, https://github.com/fermarsan/aixt.git
// Author: Fernando Martínez Santa
// Date: 2023-2024
// License: MIT
module aixt_cgen

// init_output_file initializes the output file stream.
fn (mut gen Gen) init_output_file() {
	gen.out += '// This '
    gen.out += match gen.setup.value('backend').string() {
		'nxc' 		{ 'NXC ' }
		'arduino'	{ 'Arduino ' }  
		else 		{ 'C ' }
	}
    gen.out += 'code was automatically generated by Aixt Project\n'
	gen.out += '// Device = ${gen.setup.value('device').string()}\n'
	gen.out += '// Board = ${gen.setup.value('board').string()}\n'
	gen.out += '// Backend = ${gen.setup.value('backend').string()}\n\n'

	gen.out += '\n___preprocessor_block___\n' 
	// gen.out += '\n___includes_block___\n'
	// gen.out += '\n___macros_block___\n' 
	gen.out += '\n___definitions_block___\n\n'
 
    // for h in gen.setup.value('includes').array() {	// append the header files
	// 	if h.string() != '' {
    //     	gen.add_include(h.string())
	// 	}
	// }
    // for c in gen.setup.value('configuration').array() {	// append the configuration lines
	// 	if c.string() != '' {
    // 	    gen.macros << '${gen.setup.value('config_operator').string()} ${c.string()}\n'    
	// 	}
	// }
    // for m in gen.setup.value('macros').array() {	// append the macros
	// 	if m.string() != '' {
	// 		gen.macros << '#define ${m.string()}\n'
	// 	}
	// }
}