// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c


#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#if defined(__linux) || defined(linux)
#define CLEAR_SCREEN    "clear" // for Linux
#else
#define CLEAR_SCREEN    "cls"   // for Windows
#endif
#include <string.h>
#define uart__print(MESSAGE)		printf("\033[1;32m");	printf("%s", MESSAGE)	// in green
#define uart__println(MESSAGE)		printf("\033[1;32m");	printf("%s\n", MESSAGE)	// in green

void main__init() ;
void uart__init() ;
// char *uart__input(char *msg) ;
int __t1;
char __temp_str[80];

enum main__Pin_names {
a = 0,
b,
c,
d,
w,
x,
y,
z,
};


void main__init() {
    printf("\033[1;37m");    // white bold text in terminal
}


void uart__init() {
	printf("\033[1;32m");	// print in green
	printf(" Aixt virtual UART\n");
}


// char *uart__input(char *msg) {
//     printf("\033[1;32m");	// print in green
//     printf("%s ", msg);
//     scanf("%s", __temp_str);
//     return __temp_str;
// }


int main() {
main__init();
uart__init();
long arr[4] = {2, 4, 9, 7};
for(int __t1 = 0; __t1 < 4; __t1++) {
long a;
a = arr[__t1];
a++;
sprintf(__temp_str, "value : %d", (int)a);
uart__println(__temp_str);
}
return 0;
}