// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = Emu
// Board = Linux, Windows and Android
// Backend = c

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000
i32 pin__pins[8] = {0, 0, 0, 0, 0, 0, 0, 0};
int_literal pin__input_value = (int_literal)(0);

typedef struct pin_oop__Pin pin_oop__Pin;
void  pin_oop__update();
void  pin_oop__init();
pin_oop__Pin  pin_oop__Pin__static__new(u8 id);
void  pin_oop__Pin_high(pin_oop__Pin *pin);
void  pin_oop__Pin_low(pin_oop__Pin *pin);
i32  pin_oop__Pin_read(pin_oop__Pin *pin);
void  pin_oop__Pin_toggle(pin_oop__Pin *pin);
void  pin_oop__Pin_write(pin_oop__Pin *pin, i32 val);
void  time__sleep(i32 ts);
void  time__sleep_ms(i32 tms);
void  main__init();
void  main__clear_screen();

const i32 _const_pin_oop__a = (i32)(0);
const i32 _const_pin_oop__b = (i32)(1);
const i32 _const_pin_oop__c = (i32)(2);
const i32 _const_pin_oop__d = (i32)(3);
const i32 _const_pin_oop__w = (i32)(4);
const i32 _const_pin_oop__x = (i32)(5);
const i32 _const_pin_oop__y = (i32)(6);
const i32 _const_pin_oop__z = (i32)(7);


struct pin_oop__Pin {
	i32 id;
};

void  pin_oop__update() {
	system("clear");; 
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n"); 
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n"); 
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n"); 
	for( int i = 0; i < 8; i ++ ) { 
		printf("| [");  
		if( i <= 3 ) { 
			printf("\033[1;32m");  
		} 
		else { 
			printf("\033[1;31m");  
		};  
		if( pin__pins[i] == 0 ) { 
			printf(" ");  
		} 
		else { 
			printf("#");  
		};  
		printf("\033[1;37m");  
		printf("] ");  
	} 
	printf("|\n"); 
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n"); 
}

void  pin_oop__init() {
	pin_oop__update(); 
}

inline pin_oop__Pin  pin_oop__Pin__static__new(u8 id) {
	return ((pin_oop__Pin) { 
		id,	// id = id 
	}); 
}

inline void  pin_oop__Pin_high(pin_oop__Pin *pin) {
	pin__pins[pin->id] = (i32)(1); 
	pin_oop__update(); 
}

inline void  pin_oop__Pin_low(pin_oop__Pin *pin) {
	pin__pins[pin->id] = (i32)(0); 
	pin_oop__update(); 
}

inline i32  pin_oop__Pin_read(pin_oop__Pin *pin) {
	pin__input_value = (i32)(0); 
	system("clear");; 
	printf(" Aixt virtual pins input	  pin %d : ", pin->id); 
	scanf("%ld", &pin__input_value); 
	if( pin__input_value == 0 ) { 
		pin__pins[pin->id] = (i32)(0);  
	} 
	else { 
		pin__pins[pin->id] = (i32)(1);  
	}; 
	pin_oop__update(); 
	return ((i32) pin__input_value); 
}

inline void  pin_oop__Pin_toggle(pin_oop__Pin *pin) {
	pin__pins[pin->id] ^= (i32)((i32)(1)); 
	pin_oop__update(); 
}

inline void  pin_oop__Pin_write(pin_oop__Pin *pin, i32 val) {
	pin__pins[pin->id] = (i32)(val); 
	pin_oop__update(); 
}

;

void  time__sleep(i32 ts) {
	sleep(ts);; 
}

void  time__sleep_ms(i32 tms) {
	usleep(tms * 1000);; 
}

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	system("clear");; 
}

int main() {
	pin_oop__init();
	main__init();
	pin_oop__Pin green_led = (pin_oop__Pin){
		_const_pin_oop__a,	// id = _const_pin_oop__a
	}; 
	pin_oop__Pin red_led = (pin_oop__Pin)pin_oop__Pin__static__new(_const_pin_oop__w); 
	pin_oop__update(); 
	time__sleep_ms(1000); 
	pin_oop__Pin_high(&green_led); 
	pin_oop__Pin_write(&red_led, 1); 
	time__sleep(1); 
	pin_oop__Pin_low(&green_led); 
	time__sleep(1); 
	pin_oop__Pin_write(&red_led, 0); 
	return 0;
}

