// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = emu
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#include <string.h>

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000
void  main__init();
void  main__clear_screen();

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	system("clear");; 
}

int main() {
	main__init();
	i32 aa = (i32)(245); 
	f64 xx = (f64)(3.5);
	f64 yy = (f64)(.46);
	f64 zz = (f64)(10.); 
	f64 k = (f64)(15e-4);
	f64 l = (f64)(1.2e-3);
	f64 m = (f64)(1e6); 
	bool flag_1 = (bool)(true);
	bool flag_2 = (bool)(false); 
	char str_1[120];
	strcpy(str_1, "char string");
	rune c_1 = (rune)('X'); 
	return 0;
}

