// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c


#include "CH57x_common.h"
#define true 1
#define uart2.println(MSG)		uart2.print(MSG);  uart2.write('\n');  uart2.write('\r')
#define uart2.any() R8_UART2_RFC
#define	uart2.write(DATA)	R8_UART2_THR = DATA
#define	irq__uart2_rx_enable()	UART2_ByteTrigCfg(UART2_7BYTE_TRIG);  UART2_INTCfg(ENABLE, RB_IER_RECV_RDY | RB_IER_LINE_STAT);  PFIC_EnableIRQ(UART0_IRQn)
#define irq_uart2_rx(FN_NAME)	void isr_uart2_rx(void)

void uart2.print(char* msg);
uint8_t uart2.read(void);
void uart2.setup(uint32_t baud_rate);
char input = ' ';
#define irq_uart2_rx_isr_exists
irq_uart2_rx(uart2_eco) {
input = uart2.read();
uart2.write((uint8_t)(input) + 1);
}



void uart2.print(char* msg){
    while(*msg != '\0'){
        uart2.write(*msg);
        msg++;
    }
}

uint8_t uart2.read(void){
    while(!(R8_UART2_RFC == 1)){}
    return R8_UART2_RBR; 
}


void uart2.setup(uint32_t baud_rate){
    UART2_BaudRateCfg(baud_rate);
    R8_UART2_FCR = (2 << 6) | RB_FCR_TX_FIFO_CLR | RB_FCR_RX_FIFO_CLR | RB_FCR_FIFO_EN;
    R8_UART2_LCR = RB_LCR_WORD_SZ;
    R8_UART2_IER = RB_IER_TXD_EN;
    R8_UART2_DIV = 1;

    GPIOB_SetBits(GPIO_Pin_7);
    GPIOB_ModeCfg(GPIO_Pin_4, GPIO_ModeIN_PU);   //RX
    GPIOB_ModeCfg(GPIO_Pin_7, GPIO_ModeOut_PP_5mA);  //TX
}


__attribute__((interrupt("WCH-Interrupt-fast")))
__attribute__((section(".highcode")))
void irq__global_isr(void) {
    #ifdef irq_uart2_rx_isr_exists
        if(UART2_II_RECV_TOUT) {
            isr_uart2_rx();
        }
    #endif
   return;
}




int main(void) {

uart2.setup(115200);
irq__uart2_rx_enable();
while(true) {
}
return 0;
}
