// This C code was automatically generated by Aixt Project
// Device = x64
// Board = PC
// Backend = pc

#include <stdbool.h>


int main() {
	long a[5] = {1, 3, 4, 5, 6};
	ERROR
	long b = 3;
	ERROR
	b = a[4];
	return 0;
}