// This C code was automatically generated by Aixt Project
// Device = x64
// Board = PC
// Backend = pc

#include <stdbool.h>


int main() {
	long x = 0;
	for(int i=0; i<main.repetitions; i++) {
		x += (main.e * main.e) + (main.pi / 2);
	}
	return 0;
}