// This C code was automatically generated by Aixt Project
// Device = x64
// Board = PC
// Backend = pc

#include <stdbool.h>


#include "/home/aixt-project/time__sleep.c"
#include "/home/aixt-project/machine.c"

int main() {
	float a = 0.0;
	while(true) {
		sleep(1);
		a++;
	}
	return 0;
}