// This C code was automatically generated by Aixt Project
// Device = x64
// Board = PC
// Backend = pc

#include <stdbool.h>



int main() {
	long a = 0;
	while(true) {
		sleep(1);
		a++;
	}
	return 0;
}