// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>


#include "/home/aixt-project/ports/PC/api/time__sleep.c"
#include "/home/aixt-project/ports/PC/api/machine.c"

int main() {
	float a = 0.0;
	while(true) {
		sleep(1);
		a++;
	}
	return 0;
}