// This C code was automatically generated by Aixt Project
// Device = x64
// Board = x64-based board
// Backend = pc

#include <stdbool.h>


#include "/home/aixt-project/ports/PC/api/time/sleep_ms.c"
#include "/home/aixt-project/ports/PC/api/machine/pin.c"

int main() {
	for(int i=0; i<5; i++) {
		pin_high(A);
		sleep_ms(1);
		pin_low(A);
		sleep_ms(1);
	}
	return 0;
}