// This C code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = PIC16F873
// Board = ---
// Backend = c

#include <xc.h>
#include <stdbool.h>
#include <stdint.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

#define _XTAL_FREQ _const_main__cpu_freq

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled)
#pragma config PWRTE = ON       // Power-up Timer Enable bit (PWRT disabled)
#pragma config BOREN = OFF      // Brown-out Reset Enable bit (BOR disabled)
#pragma config LVP = OFF        // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3 is digital I/O, HV on MCLR must be used for programming)
#pragma config CPD = OFF        // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF        // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF         // Flash Program Memory Code Protection bit (Code protection off)

#define time__sleep(ts) __delay_ms(ts << 10)

#define time__sleep_ms(tms) __delay_ms(tms)

#define time__sleep_us(tus) __delay_us(tus)

#define uart__read() \
while( RCIF == 0 ) { \
} \
if( OERR == 1 ) { \
	CREN = 0;  \
	CREN = 1;  \
}; \
 (u8)(RCREG); \
// end #define

#define uart__any()  RCIF == 1

#define uart__println(msg) \
uart__print(msg); \
uart__write('\n'); \
uart__write('\r'); \
// end #define

#define uart__write(ch) \
while( TRMT == 0 ) { \
} \
TXREG = ch; \
// end #define

#define uart__print(msg) 

#define uart__setup(baudrate) \
i16 x = (i16)(0); \
x = (i16)((u8)((u32)(_XTAL_FREQ) / (baudrate << 4)) - 1); \
if( x < 0 ) { \
	x = (i16)(0);  \
}; \
if( x > 255 ) { \
	x = (i16)((u8)((u32)(_XTAL_FREQ) / (baudrate << 6)) - 1);  \
	if( x > 255 ) { \
		x = (i16)(255);  \
	};  \
	BRGH = 0;  \
} \
else { \
	BRGH = 1;  \
}; \
SPBRG = (u8)(x); \
BRGH = 0; \
SYNC = 0; \
TXEN = 1; \
TX9 = 0; \
RX9 = 0; \
CREN = 1; \
SPEN = 1; \
// end #define

#define _const_pin__a0 0
#define _const_pin__a1 1
#define _const_pin__a2 2
#define _const_pin__a3 3
#define _const_pin__a4 4
#define _const_pin__a5 5
#define _const_pin__a6 6
#define _const_pin__a7 7
#define _const_pin__b0 8
#define _const_pin__b1 9
#define _const_pin__b2 10
#define _const_pin__b3 11
#define _const_pin__b4 12
#define _const_pin__b5 13
#define _const_pin__b6 14
#define _const_pin__b7 15
#define _const_pin__c0 16
#define _const_pin__c1 17
#define _const_pin__c2 18
#define _const_pin__c3 19
#define _const_pin__c4 20
#define _const_pin__c5 21
#define _const_pin__c6 22
#define _const_pin__c7 23
#define _const_pin__d0 24
#define _const_pin__d1 25
#define _const_pin__d2 26
#define _const_pin__d3 27
#define _const_pin__d4 28
#define _const_pin__d5 29
#define _const_pin__d6 30
#define _const_pin__d7 31
#define _const_pin__e0 32
#define _const_pin__e1 33
#define _const_pin__e2 34
#define _const_pin__e3 35
#define _const_pin__e4 36
#define _const_pin__e5 37
#define _const_pin__e6 38
#define _const_pin__e7 39
#define _const_pin__irq 8
#define _const_pin__output 0
#define _const_pin__input 1

#define pin__read(name)  (u8)((*(&PORTA + (name >> 3)) >> (name - ((name >> 3) << 3))) & 0x01)

#define pin__toggle(name) *(&PORTA + (name >> 3)) ^= 0x01 << (name - ((name >> 3) << 3))

#define pin__low(name) *(&PORTA + (name >> 3)) &= ~(0x01 << (name - ((name >> 3) << 3)))

#define pin__write(name, value) \
*(&PORTA + (name >> 3)) &= (~(0x01 << (name - ((name >> 3) << 3)))); \
*(&PORTA + (name >> 3)) |= (value << (name - ((name >> 3) << 3))); \
// end #define

#define pin__setup(name, mode) \
if( mode == 1 ) { \
	*(&TRISA + (name >> 3)) |= (0x01 << (name - ((name >> 3) << 3)));  \
} \
else { \
	*(&TRISA + (name >> 3)) &= ~(0x01 << (name - ((name >> 3) << 3)));  \
}; \
// end #define

#define pin__high(name) *(&PORTA + (name >> 3)) |= 0x01 << (name - ((name >> 3) << 3))

 void main(void) {
	pin__setup(_const_pin__c6, _const_pin__output); 
	uart__setup(115200); 
	while( true ) {
		uart__write('x'); 
		time__sleep_ms(500); 
	} 
}

