// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c

#include "CH57x_common.h"
#define true 1
#define a A
#define b B
#define port.output    GPIO_ModeOut_PP_5mA
#define port.input     	GPIO_ModeIN_Floating
#define port.in_pullup		GPIO_ModeIN_PU
#define port.in_pulldown	GPIO_ModeIN_PD
#define port.read(PORT) GPIO##PORT##_ReadPort()
#define port.setup_(PORT, BITS, MODE) GPIO##PORT##_ModeCfg(BITS, MODE)
#define port.setup(PORT, BITS, MODE)  port.setup_(PORT, BITS, MODE)
#define port.write_(PORT, BITS) GPIO##PORT##_SetBits(BITS)
#define port.write(PORT, BITS)  port.write_(PORT, BITS)
#define time.sleep_ms(TIME)    DelayMs(TIME)

void main__init();

void port.init();

void time.init();

void main__init() {
	port.init();
	time.init();
	
}

void port.init() {
}

void time.init() {
}

int main(void) {
    SetSysClock(CLK_SOURCE_PLL_60MHz);

	main__init();
	port.setup(a, 0x00000800, port.output);
	port.setup(b, 0xFFFFFFFF, port.output);
	while(true) {
		port.write(a, 0x00000800);
		time.sleep_ms(500);
		port.write(b, 0x00000800);
		time.sleep_ms(500);
	}
	return 0;
}
