

void pin__update() {
	system(clear_screen);
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n");
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n");
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n");
	for(int i=0; i<8; i++) {
		printf("| [");
		if(i <= 3) {printf("\033[1;32m");}else {printf("\033[1;31m");};
		if(pin__pins[i] == 0) {printf(" ");}else {printf("#");};
		printf("\033[1;37m");
		printf("] ");
	}
	printf("|\n");
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n");
}

void pin__init() {
	pin__update();
}
// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#if defined(__linux) || defined(linux)
#define clear_screen    "clear" // for Linux
#else
#define clear_screen    "cls"   // for Windows
#endif

void main__init();

#if defined(__linux) || defined(linux)
#include <unistd.h>
#else
#include <windows.h>
#endif

// sleep_ms is a delay function in milliseconds for the Aixt PC port. 
#if defined(__linux) || defined(linux)
#define time__sleep_ms(TMS)		usleep(TMS*1000)
#else
#define time__sleep_ms(TMS)		Sleep(TMS)
#endif

// #define time__sleep_ms(TMS)  start_time = clock();  while (clock() < start_time + TMS*1000)

// sleep is a delay function in seconds for the Aixt PC port. 
#if defined(__linux) || defined(linux)
#define time__sleep(TS)		sleep(TS)
#else
#define time__sleep(TS)		Sleep(TS*1000)     
#endif
// #define time__sleep(TMS)  start_time = clock();  printf("\nt = %lu\n", start_time); while (clock() < start_time + TMS*1000000)

// pin names
#define pin__a  0
#define pin__b  1
#define pin__c  2
#define pin__d  3
#define pin__w  4
#define pin__x  5
#define pin__y  6
#define pin__z  7

long pin__pins[] = {0, 0, 0, 0, 0, 0, 0, 0};
long pin__input = 0;

void pin__update();

void pin__init();

void main__init() {
	printf("\033[1;37m");
}

int main() {
	main__init();
	pin__init();
	for(int _=0; _<5; _++) {
		time__sleep(1);
		time__sleep(1);
	}
	return 0;
}

void pin__update() {
	system(clear_screen);
	printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n");
	printf(" _____ _____ _____ _____ _____ _____ _____ _____\n");
	printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n");
	for(int i=0; i<8; i++) {
		printf("| [");
		if(i <= 3) {printf("\033[1;32m");}else {printf("\033[1;31m");};
		if(pin__pins[i] == 0) {printf(" ");}else {printf("#");};
		printf("\033[1;37m");
		printf("] ");
	}
	printf("|\n");
	printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n");
}

void pin__init() {
	pin__update();
}
