// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c


#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#if defined(__linux) || defined(linux)
#define CLEAR_SCREEN    "clear" // for Linux
#else
#define CLEAR_SCREEN    "cls"   // for Windows
#endif
#if defined(__linux) || defined(linux)
#include <unistd.h>
#else
#include <windows.h>
#endif
#if defined(__linux) || defined(linux)
#define time__sleep_ms(TMS)		usleep(TMS*1000)
#else
#define time__sleep_ms(TMS)		Sleep(TMS)
#endif
#if defined(__linux) || defined(linux)
#define time__sleep(TS)		sleep(TS)
#else
#define time__sleep(TS)		Sleep(TS*1000)
#endif
#define pin__a  0
#define pin__b  1
#define pin__c  2
#define pin__d  3
#define pin__w  4
#define pin__x  5
#define pin__y  6
#define pin__z  7

void main__init() ;
long pins__[] = {0, 0, 0, 0, 0, 0, 0, 0};long input__ = 0;
void pin__update() ;
void pin__init();

void pin__high(long pin__name);

void pin__toggle(long pin__name);

void pin__low(long pin__name);

void pin__write(long pin__name, long pin__val);




void main__init() {
    printf("\033[1;37m");    // white bold text in terminal
}


void pin__update() {
    system(CLEAR_SCREEN);
    printf(" Aixt virtual pins     [#] = ON   [ ] = OFF\n");
    printf(" _____ _____ _____ _____ _____ _____ _____ _____\n");
    printf("|  a  |  b  |  c  |  d  |  w  |  x  |  y  |  z  |\n");
    for(int i__ = 0; i__<=7; i__++) {
        printf("| [");
        if(i__ <= 3) {
            printf("\033[1;32m");    // green
        } else {
            printf("\033[1;31m");    // red
        }
        if(pins__[i__] == 0) {
            printf(" ");
        } else {
            printf("#");
        }
        printf("\033[1;37m");    // white
        printf("] ");
    }
    printf("|\n");
    printf("'-----'-----'-----'-----'-----'-----'-----'-----'\n");
}


void pin__init() {
pin__update();
}


void pin__high(long pin__name) {
pins__[name] = 1;
pin__update();
}


void pin__toggle(long pin__name) {
pins__[name] ^= 1;
pin__update();
}


void pin__low(long pin__name) {
pins__[name] = 0;
pin__update();
}


void pin__write(long pin__name, long pin__val) {
pins__[name] = val;
pin__update();
}


int main() {
main__init();
pin__init();
for(int _=0; _<5; _++) {
pin__high(x);
time__sleep_ms(500);
pin__low(x);
time__sleep_ms(500);
}
return 0;
}