// This C code was automatically generated by Aixt Project
// Device = Emulator
// Board = Software Emulator
// Backend = c

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

void main__init();

long adc__read(long channel);

long value__ = 0;

enum main__Pin_names {
	a = 0,
	b,
	c,
	d,
	w,
	x,
	y,
	z,
};

void main__init() {
}

long adc__read(long channel) {
	system("clear");
	printf(" Aixt virtual ADC input     ADC %ld : ", channel);
	scanf("%ld", &value__);
	return value__;
}
enum ports__Emulator__api__adc__Channel_names {
	ch_0 = 0,
	ch_1,
};

int main() {
	main__init();
	long j = 0;
	long k = 0;
	j = adc__read(ch_0);
	k = adc__read(ch_1);
	return 0;
}
