// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = Emulator
// Board = Linux, Windows and Android
// Backend = c

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int64_t isize;
typedef int64_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint64_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000
void  main__init();
void  main__clear_screen();
char uart__buffer[] = "";

void  uart__init();
void  uart__print(char msg[]);
void  uart__println(char msg[]);
char*  uart__input(char msg[]);

void  main__init() {
	printf("\033[1;37m"); 
}

void  main__clear_screen() {
	system("clear");; 
}

void  uart__init() {
	printf("\033[1;32m"); 
	printf(" Aixt virtual UART\n"); 
}

void  uart__print(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s", msg); 
}

void  uart__println(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s\n", msg); 
}

char*  uart__input(char msg[]) {
	printf("\033[1;32m"); 
	printf("%s ", msg); 
	scanf("%s", uart__buffer); 
	return ((string) uart__buffer); 
}

int main() {
	main__init();
	uart__init();
	uart__println("Aixt on Linux (Emulator target)");; 
	char msg[120];
	strcpy(msg, "Custom flag"); 
	uart__println(msg); 
	return 0;
}

