# Project Name: Aixt, https://github.com/fermarsan/aixt.git
# Author: Fernando Martínez Santa
# Date: 2023-2024
# License: MIT
#
# Description: Setup file for the Emulator port. It works on Linux and Windows 
#              PCs and on Android with Termux

port =    "Emulator" 
board =   "Linux, Windows and Android"
backend = "c"

cc_linux =   "gcc"
cc_windows = "c:\\v\\thirdparty\\tcc\\tcc.exe"
cc_flags =   ""
cc_output_flag = "-o"
cc_input_flag = ""

api_paths = [
    "Emulator"
]

# defines = [
#     "flag_1",
# ]

string_default_len = 80
array_default_len = 20

compiler_setup_path = "setup/gcc-tcc.toml"
