# Project Name = Aixt, https://github.com/fermarsan/aixt.git
# Author = Fernando Martínez Santa
# Date = 2024
# License = MIT
#
# Description = Complete list of devices equivalences

[devices]

"PIC16F83"  = "PIC16F8x"
"PIC16F84"  = "PIC16F8x"
"PIC16F83A" = "PIC16F8x"
"PIC16F84A" = "PIC16F8x"

"PIC16F627"  = "PIC16F6xx"
"PIC16F628"  = "PIC16F6xx"
"PIC16F676"  = "PIC16F6xx"
"PIC16F627A" = "PIC16F6xx"
"PIC16F628A" = "PIC16F6xx"
"PIC16F676A" = "PIC16F6xx"

"PIC16F873"  = "PIC16F8xx"
"PIC16F874"  = "PIC16F8xx"
"PIC16F876"  = "PIC16F8xx"
"PIC16F877"  = "PIC16F8xx"
"PIC16F882"  = "PIC16F8xx"
"PIC16F883"  = "PIC16F8xx"
"PIC16F884"  = "PIC16F8xx"
"PIC16F886"  = "PIC16F8xx"
"PIC16F887"  = "PIC16F8xx"
"PIC16F873A" = "PIC16F8xx"
"PIC16F874A" = "PIC16F8xx"
"PIC16F876A" = "PIC16F8xx"
"PIC16F877A" = "PIC16F8xx"
"PIC16F882A" = "PIC16F8xx"
"PIC16F883A" = "PIC16F8xx"
"PIC16F884A" = "PIC16F8xx"
"PIC16F886A" = "PIC16F8xx"
"PIC16F887A" = "PIC16F8xx"