// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = PIC16F873
// Board = ---
// Backend = c

#include <xc.h>
#include <stdbool.h>
#include <stdint.h>

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _const_pin_fn__a0 0
#define _const_pin_fn__a1 1
#define _const_pin_fn__a2 2
#define _const_pin_fn__a3 3
#define _const_pin_fn__a4 4
#define _const_pin_fn__a5 5
#define _const_pin_fn__b0 8
#define _const_pin_fn__b1 9
#define _const_pin_fn__b2 10
#define _const_pin_fn__b3 11
#define _const_pin_fn__b4 12
#define _const_pin_fn__b5 13
#define _const_pin_fn__b6 14
#define _const_pin_fn__b7 15
#define _const_pin_fn__c0 16
#define _const_pin_fn__c1 17
#define _const_pin_fn__c2 18
#define _const_pin_fn__c3 19
#define _const_pin_fn__c4 20
#define _const_pin_fn__c5 21
#define _const_pin_fn__c6 22
#define _const_pin_fn__c7 23
#define _const_pin_fn__d0 24
#define _const_pin_fn__d1 25
#define _const_pin_fn__d2 26
#define _const_pin_fn__d3 27
#define _const_pin_fn__d4 28
#define _const_pin_fn__d5 29
#define _const_pin_fn__d6 30
#define _const_pin_fn__d7 31
#define _const_pin_fn__e0 32
#define _const_pin_fn__e1 33
#define _const_pin_fn__e2 34
#define _const_pin_fn__irq 8
#define _const_pin_fn__output 0
#define _const_pin_fn__input 1
#define _const_timer0__irq_in_use true

#define timer0__irq_disable() T0IE = 0

#define timer0__irq_enable() \
GIE = 1; \
T0IE = 1; 

#define timer0__read()  ((u8) (u8)(TMR0))

#define timer0__restart() TMR0 = (u8)(timer0__initial)

#define timer0__setup(period) \
T0CS = 0; \
if( period <= timer0__max_t_fosc(1024) ) { \
	PSA = 1;  \
	timer0__initial = (u8)(timer0__init_value(period, 2));  \
} \
else { \
	PSA = 0;  \
	OPTION_REG &= 0b11111000;  \
	if( period <= timer0__max_t_fosc(2048) ) { \
		OPTION_REG |= 0b000;  \
		timer0__initial = (u8)(timer0__init_value(period, 3));  \
	} \
	else if( period <= timer0__max_t_fosc(4096) ) { \
		OPTION_REG |= 0b001;  \
		timer0__initial = (u8)(timer0__init_value(period, 4));  \
	} \
	else if( period <= timer0__max_t_fosc(8192) ) { \
		OPTION_REG |= 0b010;  \
		timer0__initial = (u8)(timer0__init_value(period, 5));  \
	} \
	else if( period <= timer0__max_t_fosc(16384) ) { \
		OPTION_REG |= 0b011;  \
		timer0__initial = (u8)(timer0__init_value(period, 6));  \
	} \
	else if( period <= timer0__max_t_fosc(32768) ) { \
		OPTION_REG |= 0b100;  \
		timer0__initial = (u8)(timer0__init_value(period, 7));  \
	} \
	else if( period <= timer0__max_t_fosc(65536) ) { \
		OPTION_REG |= 0b101;  \
		timer0__initial = (u8)(timer0__init_value(period, 8));  \
	} \
	else if( period <= timer0__max_t_fosc(131072) ) { \
		OPTION_REG |= 0b110;  \
		timer0__initial = (u8)(timer0__init_value(period, 9));  \
	} \
	else { \
		OPTION_REG |= 0b111;  \
		timer0__initial = (u8)(timer0__init_value(period, 10));  \
	};  \
}; \
TMR0 = (u8)(timer0__initial); 

#define timer0__init_value(period, shift)  ((u8) (u8)(256 - (u16)(period >> shift) * (u16)(_const_main__cpu_freq_mhz)))

#define timer0__max_t_fosc(time)  ((u32) (u32)(time / (u8)(_const_main__cpu_freq_mhz)))

#define pin_fn__setup(id, mode) \
if( mode == 1 ) { \
	*(&TRISA + (id / 8)) |= (0x01 << (id % 8));  \
} \
else { \
	*(&TRISA + (id / 8)) &= ~(0x01 << (id % 8));  \
}; 

#define pin_fn__high(id) *(&PORTA + (id / 8)) |= 0x01 << (id % 8)

#define pin_fn__low(id) *(&PORTA + (id / 8)) &= ~(0x01 << (id % 8))

#define pin_fn__write(id, value) \
*(&PORTA + (id >> 3)) &= (~(0x01 << (id % 8))); \
*(&PORTA + (id >> 3)) |= (value << (id % 8)); 

#define pin_fn__toggle(id) *(&PORTA + (id / 8)) ^= 0x01 << (id % 8)

#define pin_fn__read(id)  ((u8) (u8)((*(&PORTA + (id / 8)) >> (id % 8)) & 0x01))

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

void (*ptr_timer0_isr)(void);
u8 timer0__initial = (u8)(0);

#define _XTAL_FREQ _const_main__cpu_freq

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled)
#pragma config PWRTE = ON       // Power-up Timer Enable bit (PWRT disabled)
#pragma config BOREN = OFF      // Brown-out Reset Enable bit (BOR disabled)
#pragma config LVP = OFF        // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3 is digital I/O, HV on MCLR must be used for programming)
#pragma config CPD = OFF        // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF        // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF         // Flash Program Memory Code Protection bit (Code protection off)

#if defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)   // if any interrupt source is activated

#ifdef _const_ext__irq_in_use
void (*ptr_ext_isr)(void);      // Interrupt Service Routine pointer
#endif  // _const_ext__irq_in_use

#ifdef _const_timer0__irq_in_use
void (*ptr_timer0_isr)(void);   // Interrupt Service Routine pointer
#endif  // _const_timer0__irq_in_use

void __interrupt() Global_ISR() {
	#ifdef _const_ext__irq_in_use
	if(INTF == 1) {
		ptr_ext_isr();
		INTF = 0;
	}
	#endif  // _const_ext__irq_in_use
	
	#ifdef _const_timer0__irq_in_use
	if(T0IF == 1) {
		ptr_timer0_isr();
		T0IF = 0;
	}
	#endif  // _const_timer0__irq_in_use
}

#endif  // defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)

bool int_flag = (bool)(false);

void  main__blinking() {
	timer0__restart(); 
	pin_fn__toggle(_const_pin_fn__c4); 
	int_flag = (bool)(true); 
}

void main(void) {
	ptr_timer0_isr = main__blinking;
	u8 count = (u8)(0); 
	pin_fn__setup(_const_pin_fn__c4, _const_pin_fn__output); 
	pin_fn__setup(_const_pin_fn__c7, _const_pin_fn__output); 
	timer0__setup(10000); 
	pin_fn__low(_const_pin_fn__c7); 
	pin_fn__low(_const_pin_fn__c4); 
	timer0__irq_enable(); 
	while( true ) {
		if( int_flag ) {
			count++; 
			if( count >= 20 ) {
				pin_fn__toggle(_const_pin_fn__c7); 
				count = (u8)(0); 
			}; 
			int_flag = (bool)(false); 
		}; 
	} 
}

