// This C code was automatically generated by Aixt Compiler
//     https://github.com/fermarsan/aixt
// Device = PIC16F874
// Board = ---
// Backend = c

#include <xc.h>
#include <stdbool.h>
#include <stdint.h>

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
// typedef NOT SUPPORTED i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
// typedef NOT SUPPORTED u64;
typedef uint8_t usize;
typedef float f32;
// typedef NOT SUPPORTED f64;
typedef float float_literal;
typedef char rune;

#define _const_port__a 0
#define _const_port__b 1
#define _const_port__c 2
#define _const_port__d 3
#define _const_port__e 4
#define _const_port__all_inputs 0b11111111
#define _const_port__all_outputs 0b00000000
#define time__sleep(ts) __delay_ms(ts << 10)
#define time__sleep_ms(tms) __delay_ms(tms)
#define time__sleep_us(tus) __delay_us(tus)
#define port__setup(id, mode) *(&TRISA + id) = mode
#define port__write(id, value) *(&PORTA + id) = value
#define port__read(id)  ((u8) (u8)(*(&PORTA + id)))
#define port__b_pullups(enable) RBPU = (i32)(!enable)

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

#define _XTAL_FREQ _const_main__cpu_freq

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled)
#pragma config PWRTE = ON       // Power-up Timer Enable bit (PWRT disabled)
#pragma config BOREN = OFF      // Brown-out Reset Enable bit (BOR disabled)
#pragma config LVP = OFF        // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3 is digital I/O, HV on MCLR must be used for programming)
#pragma config CPD = OFF        // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF        // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF         // Flash Program Memory Code Protection bit (Code protection off)

#if defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)   // if any interrupt source is activated

#ifdef _const_ext__irq_in_use
void (*ptr_ext_isr)(void);      // Interrupt Service Routine pointer
#endif  // _const_ext__irq_in_use

#ifdef _const_timer0__irq_in_use
void (*ptr_timer0_isr)(void);   // Interrupt Service Routine pointer
#endif  // _const_timer0__irq_in_use

void __interrupt() Global_ISR() {
	#ifdef _const_ext__irq_in_use
	if(INTF == 1) {
		ptr_ext_isr();
		INTF = 0;
	}
	#endif  // _const_ext__irq_in_use
	
	#ifdef _const_timer0__irq_in_use
	if(T0IF == 1) {
		ptr_timer0_isr();
		T0IF = 0;
	}
	#endif  // _const_timer0__irq_in_use
}

#endif  // defined(_const_timer0__irq_in_use) || defined(_const_ext__irq_in_use)

const u8 _const_main__sequence[8] = {(u8)(0b0000), 0b0001, 0b0011, 0b0111, 0b1111, 0b1110, 0b1100, 0b1000};

void main(void) {
	port__setup(_const_port__b, 0b11110000); 
	while( true ) {
		for( int __i_1 = 0; __i_1 < 8; __i_1 ++ ) {
			u8 step = _const_main__sequence[__i_1];
			port__write(_const_port__b, step); 
			time__sleep_ms(200); 
		} 
	} 
}

