/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "PWM1.h"
#include "Clock1.h"
#include "Out_PWM1.h"
#include "Out_PWM1_aliases.h"
#include "PWM2.h"
#include "Clock2.h"
#include "Out_PWM2.h"
#include "Out_PWM2_aliases.h"
#include "Clock3.h"
#include "PWM3.h"
#include "Out_PWM3.h"
#include "Out_PWM3_aliases.h"
#include "LED5.h"
#include "LED5_aliases.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSD_LL.h"
#include "CapSense_SensingCSX_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_Centroid_LL.h"
#include "LED6.h"
#include "LED6_aliases.h"
#include "LED7.h"
#include "LED7_aliases.h"
#include "LED8.h"
#include "LED8_aliases.h"
#include "LED9.h"
#include "LED9_aliases.h"
#include "LED10.h"
#include "LED10_aliases.h"
#include "LED11.h"
#include "LED11_aliases.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "DI1.h"
#include "DI1_aliases.h"
#include "DO1.h"
#include "DO1_aliases.h"
#include "DI2.h"
#include "DI2_aliases.h"
#include "DO2.h"
#include "DO2_aliases.h"
#include "DI3.h"
#include "DI3_aliases.h"
#include "DO3.h"
#include "DO3_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "CapSense_ISR.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

