// This C code was automatically generated by Aixt Project
// Device = CH573F
// Board = device
// Backend = c

#include "CH57x_common.h"
#define true 1
#define time__sleep_ms(TIME)    DelayMs(TIME)
#define a4  A, 4
#define a5  A, 5
#define a8  A, 8
#define a9  A, 9
#define a10 A, 10
#define a11 A, 11
#define a12 A, 12
#define a13 A, 13
#define a14 A, 14
#define a15 A, 15
#define b4  B, 4
#define b7  B, 7
#define b10 B, 10
#define b11 B, 11
#define b12 B, 12
#define b13 B, 13
#define b14 B, 14
#define b15 B, 15
#define b22 B, 22
#define b23 B, 23
#define pin__output    		GPIO_ModeOut_PP_5mA
#define pin__input     		GPIO_ModeIN_Floating
#define pin__in_pullup		GPIO_ModeIN_PU
#define pin__in_pulldown	GPIO_ModeIN_PD
#define pin__setup_(port, pin, ...) GPIO##port##_ModeCfg(GPIO_Pin_##pin, ##__VA_ARGS__)
#define pin__setup(PIN_NAME, PIN_MODE)  pin__setup_(PIN_NAME, PIN_MODE)
#define pwm__write(channel, value, type, state)	PWMX_ACTOUT(CH_PWM##channel, value, type, state)

void main__init();

void time__init();

void pin__init();

void pwm__init();

void main__init() {
	time__init();
	pin__init();
	pwm__init();
	
}

void time__init() {
}

void pin__init() {
}

void pwm__init() {
}

int main(void) {
	main__init();
	pin__setup(a12, pin__output);
	int32_t value = 0;
	while(true) {
		pwm__write(4, value, High_Level, ENABLE);
		time__sleep_ms(300);
		value = value + 50;
		if(value > 250) {
			value = 0;
		}
	}
	return 0;
}
