// This C code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = CY8CKIT-145
// Board = CY8CKIT-145-40XX
// Backend = c

#include <stdint.h>
#include <stdbool.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int32_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint32_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  20000000

// Project Name: Aixt https://github.com/fermarsan/aixt.git
// Author: Fernando M. Santa - Daniel Polo - Edwin Barrera - Javier Leon - Camilo Lucas
// Date: 2022-2025
// License: MIT
//
// // Description: builtin (CY8CKIT-145-40XX)

#include "project.h"

#define INIT_INTERRUPTS()   CyGlobalIntEnable

void  main__init();

#define _const_main__led1 led1
#define _const_main__led4 led4
#define _const_main__led5 led5
#define _const_main__led6 led6
#define _const_main__led7 led7
#define _const_main__led8 led8
#define _const_main__led9 led9
#define _const_main__led10 led10
#define _const_main__led11 led11
#define _const_main__do0 12
#define _const_main__do1 13
#define _const_main__do2 14
#define _const_main__sw2 sw2
#define _const_main__di0 20
#define _const_main__di1 21
#define _const_main__di2 22
#define _const_main__btn0 23
#define _const_main__btn1 24
#define _const_main__btn2 25
#define _const_main__sld0 26
#define _const_main__sld1 27
#define _const_main__sld2 28
#define _const_main__sld3 29
#define _const_main__sld4 30

 void  main__init() {
	INIT_INTERRUPTS(); 
}

#define uart__print(message) uart_UartPutString(message)

#define uart__println(message) \
uart_UartPutString(message); \
UartPutCRLF(); \
// end #define

#define uart__read()  UartGetChar()

#define uart__setup() uart_Start()

#define uart__write(character) UartPutChar(character)

#define time__sleep_ms(tms) CyDelay(tms)

#define time__sleep_us(tus) CyDelayUs(tus)

 int main() {
	main__init();
	uart__setup(); 
	while( true ) {
		uart__print("Hola mundo...\r\n"); 
		time__sleep_ms(1000); 
	} 
	return 0;
}

