// This Arduino code was automatically generated by Aixt Project
// Device = SAMD21
// Board = Seed Studio XIAO SAMD21
// Backend = arduino

#define pin__out OUTPUT
#define pin__in INPUT
#define pin__high(PIN_NAME)		digitalWrite(PIN_NAME, HIGH)
#define pin__low(PIN_NAME)		digitalWrite(PIN_NAME, LOW)
#define pin__read(PIN_NAME)		digitalRead(PIN_NAME)
#define pin__setup(PIN_NAME, MODE)		pinMode(PIN_NAME, MODE)
#define pin__write(PIN_NAME, VALUE)		digitalWrite(PIN_NAME, VALUE)
#define adc__read(PIN_NAME)   analogRead(PIN_NAME)
#define uart__println(MESSAGE)		Serial.println(MESSAGE)
#define uart__println_1(MESSAGE)		Serial.println(MESSAGE)
#define uart__read()		Serial.read()
#define uart__ready()		Serial.available()
#define uart__ready_1()		Serial1.available()
#define uart__read_1()		Serial1.read()
#define uart__setup(BAUND_RATE)		Serial.begin(BAUND_RATE)
#define uart__setup_1(BAUND_RATE)		Serial1.begin(BAUND_RATE)

void main__init();

void pin__init();

void adc__init();

void uart__init();

int32_t val = 0;

void main__init() {
	pin__init();
	adc__init();
	uart__init();
	
}

void pin__init() {
}

void adc__init() {
}

void uart__init() {
}

void setup() {
	main__init();
	pin__setup(3, pin__out);
	pin__setup(4, pin__out);
	uart__setup(9600);
}

void loop() {
	val = adc__read(8);
	uart__println(val);
	if(val >= 700 && val <= 800) {
		pin__high(3);
		pin__low(4);
	}
	else if(val >= 1000) {
		pin__low(3);
		pin__high(4);
	}
	else {
		pin__low(3);
		pin__low(4);
	}
}
